### ISSUE TITLE
CustomFilters replace search pattern word to @##1##@ after patch

### ISSUE THREAD

**Issue by jameschase18** [Legacy-of-Sylvanaar/prat-3-0#102]
**Describe the bug**
Using the Extra Stuff -> Custom Filter inbound option and having Secondary Output option checked, the output produced will change the search Pattern to @##1##@, no matter what will be present in replacement text.

For instance having a custom filter on word 'int', receiving a message 'int me' will produce a secondary output '@##1##@ me'.

**To Reproduce**
1. Go to Prat Settings -> Extra Stuff -> Custom Filters -> Inbound. Add a new pattern for search pattern 'int'  with "Secondary Output" checked, and secondary Output in raid warning. Replacement text can be empty/%1/int/anything.
2. Whisper yourself 'test int'

**Expected behavior**
Message 'test int' popping in raid warning, instead of "test @##1##@"

**Screenshots**
https://imgur.com/a/2nEEnwF

**Version Information (please complete the following information):**
 - Wow Version: current Classic 3.4.1
 - Prat Version: 3.0.3.9.17

**Addons you are running**
Happens even if Prat is the only loaded addon.

**Comment by Spherikal** [comment]
I have the same issue on retail but not sure what's causing it.

**Comment by plusmouse** [comment]
This is fixed in the alphas and the main release. Closing.
