### ISSUE TITLE
Errors with latest WoW Classic Patch 3.4.1 (47612)

### ISSUE THREAD

**Issue by Rerox-WoW** [Legacy-of-Sylvanaar/prat-3-0#103]
With the latest WoW Classic Patch 3.4.1 (47612) the following Errors pop up repeatedly.

1x Prat-3.0-3.10.0/modules/ChatFrames.lua:625: attempt to call method 'SetMinResize' (a nil value)
[string "@Prat-3.0-3.10.0/modules/ChatFrames.lua"]:625: in function `SetParameters'
[string "@Prat-3.0-3.10.0/modules/ChatFrames.lua"]:599: in function `ConfigureAllChatFrames'
[string "@Prat-3.0-3.10.0/modules/ChatFrames.lua"]:522: in function `OnModuleEnable'
[string "@Prat-3.0-3.10.0/addon/modules.lua"]:189: in function <Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@ActionBarProfiles/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...ActionBarProfiles/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@ActionBarProfiles/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@ActionBarProfiles/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@ActionBarProfiles/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:630: in function <...ActionBarProfiles/libs/AceAddon-3.0/AceAddon-3.0.lua:615>

**Comment by plusmouse** [comment]
You're running an old version of Prat. Download the latest version from here https://www.curseforge.com/wow/addons/prat-3-0/files/4351541
