### ISSUE TITLE
Save Command History does not save as many commands as the option says

### ISSUE THREAD

**Issue by KyrosKrane** [Legacy-of-Sylvanaar/prat-3-0#105]
**Describe the bug**
Command history (accessed by doing alt-up in the chat bar) is saving 32 commands only and ignoring the configuration option.

**To Reproduce**
1. Enable the History module and set your Save Command History value to max, as in the screenshot below.
2. Type 50 different messages. (for testing purposes, you can whisper yourself numbers sequentially, starting with 1, up to 50 or so.)
3. Use alt-up to scroll past history.
4. Note that it starts cycling at 32 messages. The 33rd and earlier message in the history is lost.

I also tested it with a setting of 50 instead of the max of 500. Same result.

**Expected behavior**
The saved messages match the number specified in the settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/458727/214472488-88578fad-8b5c-4996-9f38-dbd45fd80415.png)

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`
[21:27:33] Dump: value=GetBuildInfo()
[21:27:33] [1]="10.0.5",
[21:27:33] [2]="47799",
[21:27:33] [3]="Jan 24 2023",
[21:27:33] [4]=100005
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`
[21:28:02] Dump: value=Prat.Version
[21:28:02] [1]="Prat |3.0| (|3.9.19|)"

**Addons you are running**
Tested with only Prat and Prat Libraries loaded.

**Comment by plusmouse** [comment]
I've put a fix for this issue in the latest alpha (available from Curseforge/Wago when it finishes processing)
