### ISSUE TITLE
Timestamps are not showing for human messages

### ISSUE THREAD

**Issue by prokn4h** [Legacy-of-Sylvanaar/prat-3-0#106]
**Describe the bug**
Time stamps are showing only for system messages.

**To Reproduce**
Type any message in any channel.

**Expected behavior**
You have a time stamp in front of the message.

**Screenshots**
https://i.imgur.com/nW3xXm7.png

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic): 3.4.1 classic, 47720, Jav 18 2023, 30401
 - Prat Version: "Prat |3.0| (|3.9.1|)"

**Comment by plusmouse** [comment]
This is for a really old version of Prat 3.9.1 from 2020 - the latest is 3.9.19 from 2023. Can you verify that this issue still exists with the current version of Prat?

**Comment by prokn4h** [comment]
Sorry, 3.9.19 is my version. It's bugged in the latest one.
https://i.imgur.com/dgu6L5l.png

**Comment by plusmouse** [comment]
I've added a new module "LinkInfoIcons" that should cover this use case and let you keep the timestamps:
![image](https://user-images.githubusercontent.com/60280559/218436174-fdf5c590-6206-4f50-9d37-5749594b1e21.png)

As this error is from another addon conflict, and Prat now has an alternativem I'm going to close this.

**Comment by plusmouse** [comment]
(module is in the latest alphas)

**Comment by prokn4h** [comment]
Thank you sir, I appreciate your work!
