### ISSUE TITLE
Can't promote guild members

### ISSUE THREAD

**Issue by WingcommanderIV** [Legacy-of-Sylvanaar/prat-3-0#107]
**Describe the bug**
Every time that I try to promote people in my guild while Prat is engaged, I get an error and the promotion fails.

**To Reproduce**
Be the leader of a thousand person guild, try to promote people, you get an error, it's Prat's fault, even thoguh Prat has nothign to do with guild shit. It's really frustrating

**Expected behavior**
I expect that I'd be able to promote my guild mates without turning off my chat addon... Also, I use GRM, I don't know if they are butting heads.
**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`

**Addons you are running**
GRM maybe?

**Comment by plusmouse** [comment]
Can you try turning the AltNames module off, reloading and then try again? - to check if it is that module that's causing the issue

**Comment by WingcommanderIV** [comment]
It was never on to begin with, I use a different add on for that purpose.

**Comment by WingcommanderIV** [comment]
Date: 2023-01-26 17:34:51
ID: 6
Error occured in: AddOn: Prat-3.0
Count: 1
Message: Error: AddOn Prat-3.0 attempted to call a forbidden function (GuildPromote()) from a tainted execution path.
Debug:
   [string "=[C]"]: GuildPromote()
   [string "*FriendsFrame.xml:3816_OnClick"]:1:
      [string "*FriendsFrame.xml:3816_OnClick"]:1
Locals:
None
AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AccountantClassic, vv2.12.24
  AchievementSound, v1.3
  AdvancedInterfaceOptions, v1.8.4
  Afterlife, v28.30401
  Altoholic, v3.4.002
  Atlas, vv1.52.05
  AtlasBattlegrounds, vv1.52.01
  AtlasBurningCrusade, vv1.52.01
  AtlasClassicWoW, vv1.52.01
  AtlasDungeonLocs, vv1.52.01
  AtlasOutdoorRaids, vv1.52.02
  AtlasTransportation, vv1.52.01
  AtlasWrathoftheLichKing, vv1.52.01
  AtlasLootClassic, vv3.1.0
  AtlasLootClassicData, vv3.1.0
  AtlasLootClassicDungeonsAndRaids, vv3.1.0
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.13.03
  Attune, v311
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v10.0.34
  AutoFollow, v1.3
  AutoGear, v
  AutomaticTrackingSwitcher, v1.1.1
  BagBrother, v
  Bagnon, v10.0.16
  Bartender4, v4.14.6
  BartrubySummonPet, v1.40a
  BattleGroundEnemies, v10.0.2.6
  BeanCounter, v3.4.6933 (SwimmingSeadragon)
  BetterVendorPrice, vv1.18.01
  BigWigs, vv47-classic
  Bump, v8.3.0
  ChatBarClassic, v3.22a-WotLK
  Clique, vv3.4.14-release
  DataStore, v2023.01.06
  DataStoreAchievements, v2023.01.06
  DataStoreAgenda, v3.4.001
  DataStoreAuctions, v3.4.001
  DataStoreCharacters, v2023.01.06
  DataStoreContainers, v3.4.001
  DataStoreCrafts, v3.4.001
  DataStoreCurrencies, v3.4.002
  DataStoreInventory, v3.4.001
  DataStoreMails, v2023.01.06
  DataStoreQuests, v3.4.001
  DataStoreReputations, v3.4.001
  DataStoreSpells, v2023.01.06
  DataStoreTalents, v3.4.001
  DBMCore, v6daed1e
  DBMDefaultSkin, v
  DBMEpicMusicPack, v1.5.3
  DBMLogoutTimer, vr11
  DBMSoundEventsPack, v1.6.22
  DBMStatusBarTimers, v6daed1e
  DBMTURULMusicPack, vr3
  DBMVPVEM, v3c03207
  Details, v#Details.DF.Wrath.10409.148
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyMail, v4.5.2
  Enchantrix, v3.4.6942 (SwimmingSeadragon)
  EnchantVellum, v1.3.2
  ExtraStats, v1.3.3
  FastGuildInvite, v110
  GatherLite, v6.0.8
  Gladdy, v2.23-Release
  GuildRosterManager, v1.954
  HealerProtection, v1.0.23
  Healium, v
  HHTD, v2.4.10
  HideWorldMapMinimapButton, v1.5.2
  Immersion, v1.4.21
  InstanceAchievementTracker, v4.12.0
  ItemRack, v3.75
  LeatrixMaps, v1.13.105
  LeatrixPlus, v3.0.95
  LossOfControlAnnouncer, v1.1.0
  LossOfControlMessages, v1.0.23
  Mapster, v1.10.5
  MobInfo2, v10.1.6
  NovaWorldBuffs, v2.44
  NWTankAnnouncer, v1.0.1
  Prat30, v3.9.1
  Prat30Libraries, v
  QuestAnnounce, v9.0.1.3
  Questie, v7.4.10
  QuickHeal, v
  RareScanner, v3.4.1
  ReagentData, v2.4.1
  RollTrackerClassicZ, v1.1.10
  SaySapped, v2019-08-27
  Scrap, v10.0.10
  SilverDragon, vv2023.1
  SilverDragonOverlay, vv2023.1
  SilverDragonRangeExtender, vv2023.1
  SimpleAchievementAnnounce, v0.2
  Spy, v3.1.2
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TankHelper, v1.4.4
  TFTB, v1.30
  TomCats, v2.4.11
  TomTom, vv3.3.5-release
  ValhallaGuildTools, v105
  VendorPrice, v1.6.5
  WhereGuildmates, v1.2.0
  WIM, v3.10.7
  WrathRandomMounter, v1.3.1
  XPBarText, v2.2.9 (Wrath)
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=d51)

**Comment by plusmouse** [comment]
I haven't been able to replicate it as I don't have promote/gm (or any) access to a guild on classic, so, if its OK, I'll put together various test packages for you to try to work out what causes the problem.

First up, can you run `/console taintLog 1`, trigger the error, close WoW and then upload the contents of the `WoW Directory\_classic_\Logs\taint.log` file here?

**Comment by plusmouse** [comment]
I've tested the Guild UI with a GM and they can promote/demote without issue. Going to close this as resolved unless a taint log is provided indicating where in Prat the error is coming from.
