### ISSUE TITLE
History.lua:784: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by ChilledTrong** [Legacy-of-Sylvanaar/prat-3-0#109]
@ @Describe the bug - 

error that occurs every time i log into a character that has the add-on enabled 

to reproduce - 

every log in, have 10x of them at the moment

10x Prat-3.0-3.9.19/modules/History.lua:784: attempt to concatenate a nil value
[string "@Prat-3.0-3.9.19/modules/History.lua"]:784: in function <Prat-3.0/modules/History.lua:769>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `AddHistoryLine'
[string "@Prat-3.0-3.9.19/modules/History.lua"]:733: in function `addSavedHistory'
[string "@Prat-3.0-3.9.19/modules/History.lua"]:622: in function <Prat-3.0/modules/History.lua:587>
[string "@Prat-3.0-3.9.19/modules/Scrollback.lua"]:77: in function `OnModuleEnable'
[string "@Prat-3.0-3.9.19/addon/modules.lua"]:189: in function <Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 OnSubvalueChanged = <function> defined @Prat-3.0/modules/History.lua:682
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 RestoreLastSession = <function> defined @Prat-3.0/modules/Scrollback.lua:206
 Enable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:409
 defaultModuleLibraries = <table> {
 }
 pluginopts = <table> {
 }
 Prat_FramesRemoved = <function> defined @Prat-3.0/modules/Scrollback.lua:135
 RawHookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:394
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "Prat_History"
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 AddMessage = <function> defined @Prat-3.0/modules/Scrollback.lua:142
 DisableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 db = <table> {
 }
 baseName = "Prat-3.0"
 AddHistoryLine = <function> defined @Prat-3.0/modules/History.lua:769
 Prat_FramesUpdated = <function> defined @Prat-3.0/modules/Scrollback.lua:127
 GetEntryAtIndex = <function> defined @Prat-3.0/modules/Scrollback.lua:150
 HookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:365
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 UnhookAll = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:476
 IsHooked = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:492
 addSavedHistory = <function> defined @Prat-3.0/modules/History.lua:726
 SecureHook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:335
 IsModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 saveLine = <function> defined @Prat-3.0/modules/History.lua:739
 SetDefaultModuleState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 ConfigureAllChatFrames = <function> defined @Prat-3.0/modules/History.lua:662
 OnModuleDisable = <function> defined @Prat-3.0/modules/Scrollback.lua:102
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 GetDescription = <function> defined @Prat-3.0/modules/History.lua:653
 OnModuleEnable = <function> defined @Prat-3.0/modules/Scrollback.lua:76
 PL = <table> {
 }
 hooks = <table> {
 }
 ClearHistory = <function> defined @Prat-3.0/modules/History.lua:758
 SetHistory = <function> defined @Prat-3.0/modules/History.lua:720
 IterateModules = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 OnValueChanged = <function> defined @Prat-3.0/modules/Scrollback.lua:113
 RawHook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:312
 Unhook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:417
 moduleName = "History"
 defaultModuleState = true
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
}
editBox = ChatFrame7EditBox {
 0 = <userdata>
 AddHistoryLine = <function> defined =[C]:-1
 headerSuffix = ChatFrame7EditBoxHeaderSuffix {
 }
 rDrag = Frame {

 - Wow Version: Wotlk Classic - 3.4.1 / 47720 / Jan 18 2023 / 30401
 - Prat Version: Prat |3.0| (|3.9.19|)

**Addons you are running**
If possible list which addons you were using when the bug occurred.

Addon Usage - 

Advanced Interface Options
afk full screen warning
ala trade skill
already known
atlast
atlast loot classic
attune
auctionator
bagnon
bis tooltip
blizzmove
breakables
bug grabber
bug sack
cleaner loot messages
daily to do
dejunk
details
gearquipper
grfo
handy notes
healbot
improved loot frame
instant achiev tracker
item lock
leatrix plus
message queue
Mute sound file
pawn
plain automail
postal
prat
profession cooldown tracker
quartz
questie
restocker
spell activated overlay
tocotip
tomtom
weakauras
whats training
where to gather
speed autoloot
wowpro
Dbm
lockout tracker

**Comment by plusmouse** [comment]
Can you screenshot your History module settings?
![image](https://user-images.githubusercontent.com/60280559/216788566-1591c3ef-9fdd-4cab-b662-b432317f6e33.png)
This is mine, but the error doesn't trigger.

**Comment by ChilledTrong** [comment]
![image](https://user-images.githubusercontent.com/116475228/216803272-e83f0494-6b94-4c67-ac91-8ce8e2d08a61.png)


you dont have that error because you have the set lines unticked so i dont believe its saving any only your commands

**Comment by ChilledTrong** [comment]
i think another possible problem could because the addon is called before the memory has finished loading. is there possible a way to set a bigger delay before prat loads as to have time for chat to load first?

**Comment by plusmouse** [comment]
I've added a check into Prat that should hopefully prevent the error. Please let me know how it goes. I'll post the file here when it finishes building.

**Comment by plusmouse** [comment]
[Prat-3.0-3.9.19-2-g82e487d.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/10678948/Prat-3.0-3.9.19-2-g82e487d.zip)

**Comment by ChilledTrong** [comment]
<3
