### ISSUE TITLE
Community Chats not working till you remove and readd

### ISSUE THREAD

**Issue by Doominitus** [Legacy-of-Sylvanaar/prat-3-0#110]
This may be a bug in chat itself and not a prat issue but maybe hoping prat can possibly make a fix to fix the chat if its a bug in chat. 

Sometimes when you log into the game community chat doesn't work in the chat. 
I have to hit J and remove the chat and readd it then it appears in chat again.
 
Its been happening for awhile again may not even be a prat issue but hoping maybe somehow prat can fix it so its not an issue somehow. Would be nice if prat can somehow fix it.

**Comment by plusmouse** [comment]
Can you screenshot the chat view that is glitching?

**Comment by Doominitus** [comment]
Here you go now to fix it I just click add to chat window and unclick it and reclick it and then it works fine.

![image](https://user-images.githubusercontent.com/72922317/217624661-f3612398-2c0b-408e-833e-b9b567e39f10.png)

![image](https://user-images.githubusercontent.com/72922317/217624728-e53180e5-98fe-4ea3-9ca1-2ba3d1f4663a.png)

**Comment by Doominitus** [comment]
As you can see the test isnt in my chat window if I unchecked it and rechecked it it works fine.

**Comment by plusmouse** [comment]
Can you try enabling the Memory module, saving your chat settings when you're correctly joined to the Community channel.
![image](https://user-images.githubusercontent.com/60280559/218439549-2659a9b8-993a-43d2-99de-16dd38a8dd00.png)
This will override the glitchy Blizzard default behaviour.

![image](https://user-images.githubusercontent.com/60280559/218439746-4a143034-f838-41e0-8d09-f9fd1d39ee7b.png)

**Comment by plusmouse** [comment]
Going to close this as fixed as the issue hasn't reoccurred.
