### ISSUE TITLE
Lua Error Chatframe

### ISSUE THREAD

**Issue by Ssesmar** [Legacy-of-Sylvanaar/prat-3-0#111]
1x FrameXML/ChatFrame.lua:3917: invalid option in `format'
[string "=[C]"]: in function `format'
[string "@FrameXML/ChatFrame.lua"]:3917: in function `ChatFrame_MessageEventHandler'
[string "@Prat-3.0-3.9.19/addon/addon.lua"]:680: in function <Prat-3.0/addon/addon.lua:612>
[string "=(tail call)"]: ?
[string "@FrameXML/ChatFrame.lua"]:3155: in function `ChatFrame_OnEvent'
[string "*FloatingChatFrame.xml:675_OnEvent"]:1: in function <[string "*FloatingChatFrame.xml:675_OnEvent"]:1>

Locals:
(*temporary) = "Die Anwesenheit von %n hat einen Geist in der Nähe dazu inspiriert, sich auch in den Kampf zu stürzen."
(*temporary) = "Gefallener Geist"
(*temporary) = "Gefallener Geist"

**Comment by plusmouse** [comment]
I've tested the text in the error message and it displays without issue, possibly this was an effect of an older version of Prat. If it comes up again please post the message that caused it (if you have it)
