### ISSUE TITLE
Error CustomFilters

### ISSUE THREAD

**Issue by Ssesmar** [Legacy-of-Sylvanaar/prat-3-0#113]
3x Prat-3.0-3.9.19/modules/CustomFilters.lua:1052: attempt to call a nil value
[string "@Prat-3.0-3.9.19/modules/CustomFilters.lua"]:1052: in function <Prat-3.0/modules/CustomFilters.lua:1022>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `gsub'
[string "@Prat-3.0-3.9.19/services/patterns.lua"]:197: in function `MatchPatterns'
[string "@Prat-3.0-3.9.19/addon/addon.lua"]:567: in function `ProcessUserEnteredChat'
[string "@Prat-3.0-3.9.19/addon/addon.lua"]:545: in function <Prat-3.0/addon/addon.lua:510>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4893: in function <FrameXML/ChatFrame.lua:4892>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4929: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
text = "trash"
matchopts = <table> {
 enabled = true
 sink20OutputSink = "None"
 outputmessageonly = true
 searchfor = "trash"
 replacement_is_code = true
 tosink = true
 hilight = true
 name = "trash"
 hilight_color = <table> {
 }
 replacewith = ":)"
 block = false
 sound = "Aggro"
 inchannels = <table> {
 }
}
mode = "outbound"
matchtype = "OUTBOUND"
textout = "trash"
(*temporary) = nil
(*temporary) = "trash"
(*temporary) = "attempt to call a nil value"
CLR = <table> {
 GetHashColor = <function> defined @Prat-3.0/services/textcolor.lua:94
 Player = <function> defined @Prat-3.0/modules/PlayerNames.lua:1489
 Colorize = <function> defined @Prat-3.0/services/textcolor.lua:118
 DEFAULT = "ffffff"
 GetHexColor = <function> defined @Prat-3.0/services/textcolor.lua:89
 Class = <function> defined @Prat-3.0/modules/PlayerNames.lua:1472
 Desaturate = <function> defined @Prat-3.0/services/textcolor.lua:142
 HueToColor = <function> defined @Prat-3.0/services/textcolor.lua:214
 Bracket = <function> defined @Prat-3.0/modules/PlayerNames.lua:1466
 Common = <function> defined @Prat-3.0/modules/PlayerNames.lua:1468
 HSLtoRGB = <function> defined @Prat-3.0/services/textcolor.lua:192
 LINK = <table> {
 }
 Level = <function> defined @Prat-3.0/modules/PlayerNames.lua:1475
 Random = <function> defined @Prat-3.0/modules/PlayerNames.lua:1470
 RGBtoHSL = <function> defined @Prat-3.0/services/textcolor.lua:155
}

**Comment by plusmouse** [comment]
Without any more information it isn't possible to resolve this issue. Closing
