### ISSUE TITLE
Chat position always changes

### ISSUE THREAD

**Issue by Smexhy** [Legacy-of-Sylvanaar/prat-3-0#114]
**Describe the bug**
Pretty randomly when I relog into WoW, or if I reload UI sometimes, my chat is shifting few pixels to different direction than it was after I locked the window. I tried editing chat-cache.txt manually, even tried to set it as read-only, but it will always move out of it’s position set by me. It’s pretty random though it mostly happens when relogging or reopening the game. Also if I am correct, size is always the same, only position is not saving. It’s not a big deal when you are using simple ui without any frames around the chat, but it looks bad otherwise in my case. Few other people who use elvui that I talked to have the same problem.

**To Reproduce**
1. Set size and position for your chat window
2. Exit game and reopen it, relog
3. Menu will be shifted a bit, it might be hard to see depending on the UI

**Expected behavior**
Chat position should be permanent and never changing after I move and resize it + lock it in place.

**Version Information (please complete the following information):**
 - Wow Version: (3.4.1)
 - Prat Version: Latest version - 3.9.19

**Addons you are running**
I am using many addons, but I needed to debug this issue, so I am only using elvui and prat 3.0 to test things out.

**Comment by plusmouse** [comment]
Does this issue persist when just Prat is enabled? Similarly does it persist when just ElvUI is enabled?

**Comment by plusmouse** [comment]
No response. Closing.
