### ISSUE TITLE
Prat / WIM Integration

### ISSUE THREAD

**Issue by orionshock** [Legacy-of-Sylvanaar/prat-3-0#115]
https://github.com/Legacy-of-Sylvanaar/prat-3-0/blob/bc942d52f7a506ab10a3d973325498db292e7766/addon/addon.lua#L243

the WIM module in Prat that adds Prat style formatting available in WM depends on this function being there. With out it, it errors out and WIM doesn't display any messages.

**Comment by plusmouse** [comment]
I've restored the function. Can you test the latest alpha and verify that the problem is fixed?

[Prat-3.0-3.9.20-1-g36256f2.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/10907419/Prat-3.0-3.9.20-1-g36256f2.zip)

**Comment by orionshock** [comment]
1x Prat-3.0-3.9.20-1-g36256f2/services/chatsections.lua:192: attempt to index local 's' (a function value)
[string "@Prat-3.0-3.9.20-1-g36256f2/services/chatsections.lua"]:192: in function `BuildChatText'
[string "@Prat-3.0-3.9.20-1-g36256f2/addon/addon.lua"]:279: in function <Prat-3.0/addon/addon.lua:245>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@WIM/Sources/Options/CoreOptions.lua"]:121: in function <WIM/Sources/Options/CoreOptions.lua:110>
[string "=[C]"]: in function `Show'
[string "@WIM/Sources/Options/CoreOptions.lua"]:95: in function <WIM/Sources/Options/CoreOptions.lua:93>
[string "@WIM/Sources/Options/OptionsTookKit.lua"]:200: in function `func'
[string "@DBM-Core/Libs/LibDropDownMenu-28/LibDropDownMenu.lua"]:1088: in function <...ns/DBM-Core/Libs/LibDropDownMenu/LibDropDownMenu.lua:1053>

**Comment by plusmouse** [comment]
I've uploaded another alpha, can you try this one?

**Comment by orionshock** [comment]
11x bad argument #1 to '?' (Usage: local className, classFilename, classID = C_PlayerInfo.GetClass(playerLocation))
[string "=[C]"]: in function `GetClass'
[string "@Prat-3.0-3.9.22/modules/LinkInfoIcons.lua"]:565: in function `?'
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Prat-3.0-3.9.22/addon/addon.lua"]:263: in function <Prat-3.0/addon/addon.lua:245>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@WIM/Modules/History.lua"]:244: in function `fun'
[string "@WIM/WIM.lua"]:364: in function `CallModuleFunction'
[string "@WIM/Sources/WindowHandler.lua"]:1460: in function <WIM/Sources/WindowHandler.lua:1407>
...
[string "=(tail call)"]: ?
[string "@FrameXML/ChatFrame.lua"]:4927: in function <FrameXML/ChatFrame.lua:4884>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4799: in function `ChatEdit_OnTextSet'
[string "*ChatFrame.xml:136_OnTextSet"]:1: in function <[string "*ChatFrame.xml:136_OnTextSet"]:1>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetText'
[string "@FrameXML/ChatFrame.lua"]:4159: in function `ChatEdit_OnUpdate'
[string "*ChatFrame.xml:118_OnUpdate"]:1: in function <[string "*ChatFrame.xml:118_OnUpdate"]:1>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local className, classFilename, classID = C_PlayerInfo.GetClass(playerLocation))"
