### ISSUE TITLE
lua error after update

### ISSUE THREAD

**Issue by Lagorsirion** [Legacy-of-Sylvanaar/prat-3-0#116]
persisting after reload

4x Prat-3.0-3.9.20/modules/WIM.lua:4: attempt to call field 'Format' (a nil value)
[string "@Prat-3.0-3.9.20/modules/WIM.lua"]:4: in function <Prat-3.0/modules/WIM.lua:4>
[string "=(tail call)"]: ?
[string "@WIM/Modules/History.lua"]:244: in function `fun'
[string "@WIM/WIM.lua"]:364: in function `CallModuleFunction'
[string "@WIM/Sources/WindowHandler.lua"]:1460: in function <WIM/Sources/WindowHandler.lua:1407>
[string "=(tail call)"]: ?
[string "@WIM/Modules/WhisperEngine.lua"]:200: in function <WIM/Modules/WhisperEngine.lua:179>
[string "@WIM/Modules/WhisperEngine.lua"]:338: in function `handler'
[string "@WIM/Libs/LibChatHandler-1.0-25/LibChatHandler-1.0.lua"]:267: in function <...s/WIM/Libs/LibChatHandler-1.0/LibChatHandler-1.0.lua:252>
[string "@WIM/Libs/LibChatHandler-1.0-25/LibChatHandler-1.0.lua"]:311: in function <...s/WIM/Libs/LibChatHandler-1.0/LibChatHandler-1.0.lua:299>

Locals:
smf = WIM3_msgFrame1ScrollingMessageFrame {
 0 = <userdata>
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 OnFontObjectUpdated = <function> defined =[C]:-1
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 Clear = <function> defined =[C]:-1
 shouldFadeAfterInactivity = false
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 SetFont = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = Frame {
 }
 SetShadowOffset = <function> defined =[C]:-1
 GetFont = <function> defined =[C]:-1
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 PackageEntry = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 fontObject = table: 000001E422E03310 {
 }
 overrideFadeTimestamp = 0
 SetInsertMode = <function> defined =[C]:-1
 MarkDisplayDirty = <function> defined =[C]:-1
 IsSelectingText = <function> defined =[C]:-1
 widgetName = "chat_display"
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 isLayoutDirty = true
 ScrollDown = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 isDisplayDirty = true
 SetScrollOffset = <function> defined =[C]:-1
 visibleLines = <table> {
 }
 textIsCopyable = false
 scrollOffset = 0
 fadeDurationSecs = 3
 CanEffectivelyFade = <function> defined =[C]:-1
 timeVisibleSecs = 10
 SetJustifyV = <function> defined =[C]:-1
 insertMode = 2
 AddMessage = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 GetScaledCursorPosition = <function> defined =[C]:-1
 OnPostMouseUp = <function> defined =[C]:-1
 ResetSelectingText = <function> defined =[C]:-1
 PageUp = <function> defined =[C]:-1
 SetOnDisplayRefreshedCallback = <function> defined =[C]:-1
 GetNumMessages = <function> defined =[C]:-1
 UpdateSelectingText = <function> defined =[C]:-1
 GetTextColor = <function> defined =[C]:-1
 AtBottom = <function> defined =[C]:-1
 ResetAllFadeTimes = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetScrollOffset = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 ScrollByAmount = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 CalculateLineSpacing = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 SetFadeDuration = <function> defined =[C]:-1
 AdjustMessageColors = <function> defined =[C]:-1
 InitializeFontableFrame = <function> defined =[C]:-1
 RefreshLayout = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 parentWindow = WIM3_msgFrame1 {
 }
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 GetJustifyH = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 FindCharacterAndLineIndexAtCoordinate = <function> defined =[C]:-1
 GetMaxScrollRange = <function> defined =[C]:-1
 SetJustifyH = <function> defined =[C]:-1
 AcquireFontString = <function> defined =[C]:-1
 GetShadowOffset = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetTextColor = <function> defined =[C]:-1
 UpdateFading = <function> defined =[C]:-1
 GetPagingScrollAmount = <function> defined =[C]:-1
 ScrollToTop = <function> defined =[C]:-1
 GetOnDisplayRefreshedCallback = <function> define

**Comment by plusmouse** [comment]
Can you try the latest alpha and report if it fixes the issue?

**Comment by Lagorsirion** [comment]
played 4 hours today, seems like its fixed

**Comment by plusmouse** [comment]
Great. I've pushed the change into a normal release, which will be 3.9.21 once it finishes processing. Closing this issue as solved now.
