### ISSUE TITLE
Please change "Führer" back to Mentor

### ISSUE THREAD

**Issue by Hrocks1** [Legacy-of-Sylvanaar/prat-3-0#118]
Can you pls change the word "Führer" instead of Mentor for the german client back to Mentor (beginner channel)? The word "Führer" is part of the dark nazi history of us germans, it feels very wrong to use it as a name for a wow beginner guide.

**Comment by plusmouse** [comment]
Ok. Just pushed a new build and locked the translations so they won't change again. I'll link the build here when its finished.

**Comment by plusmouse** [comment]
[Prat-3.0-3.9.24.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/11062355/Prat-3.0-3.9.24.zip)

**Comment by Devinmarra** [comment]
> Can you pls change the word "Führer" instead of Mentor for the german client back to Mentor (beginner channel)? The word "Führer" is part of the dark nazi history of us germans, it feels very wrong to use it as a name for a wow beginner guide.

I just wanted to say we're VERY sorry about that. Someone used an automatic translation tool and it must not have been proof-read for correct context. Thank you for pointing this out so quickly.
