### ISSUE TITLE
every line shows as : <BNET REMOVED>

### ISSUE THREAD

**Issue by JPEscher** [Legacy-of-Sylvanaar/prat-3-0#12]
Started on login tonight (roughly 2045 on 2022 06 10) and only goes away when disabling prat 3.0 

no errors thrown so i am unsure of what to get for you. please let me know what you'd like

**Comment by QartemisT** [comment]
This is due to ChatHistory module, and how blizzard encodes the BattleNet names, which makes them invalidate after a reload. Nothing fixable sadly.

**Comment by JPEscher** [comment]
@QartemisT i wish that you were right, but this was everything. incoming messages. bnet or not, simpley read <bnet removed>

wanting links i have since gotten another mod for that, chatcopypaste, which does not cause this. i would love to switch back to prat but if this wont be fixed then there is no way to use it as i cannot read chat

**Comment by QartemisT** [comment]
Is this still persisting on the latest release? I'm unable to replicate this at all?

**Comment by JPEscher** [comment]
will test after work.
will turn off chatcopypaste while testing to prevent interaction issues

**Comment by JPEscher** [comment]
working again. ty
