### ISSUE TITLE
Achievement not showing in chat

### ISSUE THREAD

**Issue by Dhisanas** [Legacy-of-Sylvanaar/prat-3-0#124]
**Describe the bug**
I no longer see achievement pop up in my chat not for my own nor for my guild chat/mates like they gets filtered out; i tried completing an achievement i was close to completition with prat disabled and it showed in chat, boh general and guild (the doublespam)

**To Reproduce**
I don't remember changin anything since last patch and i frankly i don't even recall update since i do an uptade all by curseclient so..

**Expected behavior**
not to act like achievement chat pop up are filtered out just like before

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`

**Addons you are running**
none that interact/blocks chat funtions, like stated above achievement chat popup works just fine with prat disabled

**Comment by plusmouse** [comment]
Can you check that this checkbox is unticked?
![image](https://user-images.githubusercontent.com/60280559/234858749-e237b328-8a1e-4148-97a9-7d618e8044c0.png)

I've gone around and got an exploration achievement and its appeared in chat, so there's going to be a setting different somewhere. Doesn't mean the setting isn't malfunctioning though.

**Comment by Dhisanas** [comment]
Hi, it is and has always been unticked, i tried to tick it on but you know, then it would work as intended right? :)
