### ISSUE TITLE
Add date to timestamp

### ISSUE THREAD

**Issue by Unplayed** [Legacy-of-Sylvanaar/prat-3-0#126]
Please add ability to put date in chat to timestamp.

Our guild is multi-regional, and when part of the guild still has April 26, another part already has April 27. It would also be useful to see the date next to the time in the chat history.

**Comment by plusmouse** [comment]
How is seeing today's date (in your current time zone) against a chat message going to help? The only time you'll notice the difference is when comparing screens between a user in another time zone.

**Comment by Unplayed** [comment]
In current chat -- agree. But in the chat history, I think it would be usefull to see the date. I keep pm history for 7 days, so I would like to see it that way:

[10.05.23][12:31:12] [W From] [70:Xxxx]: <3

To just see when it is written, and not try to count the day;)

**Comment by plusmouse** [comment]
Available in the latest alphas
![image-1](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/60280559/628a84c8-5f93-48c5-a6c1-8266daf15c09)
