### ISSUE TITLE
Fade certain buttons like search and copychat completely unless hovering

### ISSUE THREAD

**Issue by Rezy942** [Legacy-of-Sylvanaar/prat-3-0#127]
Hello,

Could you please add a way to make copychat and search buttons completely transparent when chat window is not in focus?
And when you mouse over it - the buttons will apear.
This is a bit immersion breaking for me (has been for years now).
Hopefully you could consider this... thank you

**Comment by plusmouse** [comment]
Would you be OK with having the buttons fade altogether when not hovering over the buttons themselves?

**Comment by Rezy942** [comment]
Yes that would also work! Perhaps an optional toggle in the fading settings (toggle not required if its not an easy task)

**Comment by plusmouse** [comment]
Available in the latest alpha when it finishes building
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/60280559/438375f3-d8b3-4d24-a6b9-122b0aa2c2ab)
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/60280559/4056ad93-91e5-4fe3-bf93-2272120b5615)
