### ISSUE TITLE
Prat defaults to different font style every login

### ISSUE THREAD

**Issue by Rezy942** [Legacy-of-Sylvanaar/prat-3-0#129]
Hello,

A big annoyance I have right now is that Prat seems to default to Friz Quadrata font style every login.
For example I set arial narrow font style, next login that resets back to Friz.
That is WITHOUT checking "Remember font" button.

I understand i can check that to resolve this issue - but shouldnt the default font style be blizz arial?
Any chance that can be changed so the default loaded font is blizzard new font.

Thanks

**Comment by plusmouse** [comment]
If you really don't want the Prat font, just switch the Font module off, or use the checkbox.

The font takes the default from a library, which another addon can configure to change the default. The default when no addon has set one happens to be Fritz Quadrata TT.
