### ISSUE TITLE
Add pet battle tab to font size adjustment

### ISSUE THREAD

**Issue by ghost** [Legacy-of-Sylvanaar/prat-3-0#130]
As title suggests - please add battle pet tab support in chat
![image](https://user-images.githubusercontent.com/122007087/235335228-fbb86ce5-3086-4ac0-93a1-753aa675000f.png)

I want to set font size 15 for it, but default blizz fonts are 14 or 16...

Thanks

**Comment by Rezy942** [comment]
Also if possible, an option to auto-close pet battle tab when it is created during pet battle :)
These 2 things would be great for both those that use it, and dont use it!

**Comment by plusmouse** [comment]
Font sizing is now available in the latest alpha.

Auto closing the pet battle tab is tracked in #100
