### ISSUE TITLE
Chat channels disappearing

### ISSUE THREAD

**Issue by johndolotko** [Legacy-of-Sylvanaar/prat-3-0#133]
**Describe the bug**
With Prat addon enabled my chat channels keep changing, sometimes missing altogether.  I have to continually /join each of the channels or change the order.
With Prat addon disabled, the chat channels stay the same and none are missing or out of order.

**To Reproduce**
Normally happens on each logon of any character. I can add and change the order of the chat channels but everytime i log on with another character or teh same one it messes up the chat channels with different order or sometimes missing altogether.

**Expected behavior**
Expect the chat channels to stay the same.

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: Retail 10.1.0
 - Prat Version: 3.9.26

**Addons you are running**
If possible list which addons you were using when the bug occurred.

**Comment by plusmouse** [comment]
Do you have the Memory module active? If that was active with the wrong channels saved it would cause this behavior.

**Comment by johndolotko** [comment]
thanks, that seems to have fixed it :)
