### ISSUE TITLE
Chat tabs not staying invisible in latest version

### ISSUE THREAD

**Issue by WanderingFox** [Legacy-of-Sylvanaar/prat-3-0#135]
**Describe the bug**
As of the latest version (3.9.28) chat tabs suddenly ignore 0 alpha settings and just behave like standard rather than the expected behavior of staying hidden.

**To Reproduce**
1. Go to chat tab module and uncheck all chat tabs
2. Set active alpha and not active alpha to 0
3. Hover over a chat frame and note that chat tabs become visible

**Expected behavior**
Chat tabs should not become visible

**Screenshots**
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/2967926/311e963b-efa3-42c5-8c02-81010b7de530)
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/2967926/e71b6460-a460-48b5-ace0-7964ae0fd0c9)

**Version Information (please complete the following information):**
 - Wow Version: current Retail
 - Prat Version: Prat 3.9.28

**Addons you are running**
Happens with just prat installed

**Comment by plusmouse** [comment]
I've added a fix in the latest alpha. Deleted a weird:
```lua
tabButton:Show()
tabButton:Hide()
```
from the old code without realising it was needed for the tab configuration. Added it back.

**Comment by plusmouse** [comment]
[Prat-3.0-3.9.28-2-g77b865c.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/11593556/Prat-3.0-3.9.28-2-g77b865c.zip)
