### ISSUE TITLE
3.9.29 - Tabs Non Active Alpha doesn't apply to dropdown menu

### ISSUE THREAD

**Issue by bunghead** [Legacy-of-Sylvanaar/prat-3-0#136]
The little arrow that opens a dropdown menu when there's too many chat tabs doesn't fully disappear anymore when "Not Active Alpha" is set to 0 under "Display Settings" -> "Tabs".

If I'm not mistaken, I was able to make it disappear prior to 3.9.29, by moving the mouse over and away from chat.

(Prat 3.9.29, WoW Retail)

**Comment by plusmouse** [comment]
A fix is in the latest alpha available when the build system finishes processing it from Curseforge/Wago
