### ISSUE TITLE
Color Names Everywhere

### ISSUE THREAD

**Issue by zeenk** [Legacy-of-Sylvanaar/prat-3-0#139]
Noticed my chat only shows names in green instead of class color like it does in the addon screenshot here:
![WoWScrnShot_043009_125144](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/68170439/2d4d8872-2b38-42dd-9583-6cf924fdc56d)

Mine just looks like this: 
![2023-07-04_20-55-52](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/68170439/2efd2b1a-8acb-4112-bdc2-0f908f8978f6)
I have "Color Names Everywhere" in PlayerNames/Chat formatting setting and also tried the console command ```/console SET chatClassColorOverride "0"``` but still shows as green when you type player names :/

Any ideas what could cause that?

**Comment by plusmouse** [comment]
This behaviour only applies to the current character's name and is caused by this option being on:
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/60280559/e9b787cf-1c1d-4fdb-979a-497b68828d9d)
