### ISSUE TITLE
Error on login without doing anything

### ISSUE THREAD

**Issue by Knakriktsur** [Legacy-of-Sylvanaar/prat-3-0#140]
WOTLK 3.4.2.50250
Ger Client
Bagnon "Bagnon-10.0.16 for wow-3.4.1"

Hi when I login wothout doing anything I get this error message:

1x FrameXML/FloatingChatFrame.lua:973: attempt to index local 'self' (a nil value)
[string "@FrameXML/FloatingChatFrame.lua"]:973: in function <FrameXML/FloatingChatFrame.lua:968>
[string "=[C]"]: in function `FCF_SetChatWindowFontSize'
[string "@Prat-3.0-3.9.31/modules/Font.lua"]:722: in function `SetFontSize'
[string "@Prat-3.0-3.9.31/modules/Font.lua"]:710: in function `ConfigureAllChatFrames'
[string "@Prat-3.0-3.9.31/modules/ChatFrames.lua"]:638: in function <Prat-3.0/modules/ChatFrames.lua:632>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `FloatingChatFrame_UpdateBackgroundAnchors'
[string "@Interface_WrathBlizzard_CombatLog/Blizzard_CombatLog.lua"]:3348: in function <...athBlizzard_CombatLog/Blizzard_CombatLog.lua:3334>
[string "@Interface_WrathBlizzard_CombatLog/Blizzard_CombatLog.lua"]:3403: in function `FCF_DockUpdate'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2707: in function `UIParentManageFramePositions'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:1958: in function <Interface_Wrath/FrameXML/UIParent.lua:1945>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2714: in function <Interface_Wrath/FrameXML/UIParent.lua:2712>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@FrameXML/BuffFrame.lua"]:379: in function `BuffFrame_UpdateAllBuffAnchors'
[string "@FrameXML/BuffFrame.lua"]:120: in function `BuffFrame_Update'
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:75: in function <...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:74>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@SharedXML/CvarUtil.lua"]:114: in function <SharedXML/CvarUtil.lua:106>

Locals:
self = nil
chatFrame = ChatFrame10 {
 0 = <userdata>
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 tellTimer = 4510.764000
 fadeDurationSecs = 3
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 4519.267000
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 CanEffectivelyFade = <function> defined =[C]:-1
 print = <function> defined @Prat-3.0/services/print.lua:47
 OnPreSizeChanged = <function> defined =[C]:-1
 GetScrollOffset = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "Chat 10"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined =[C]:-1
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 originalShow = <function> defined =[C]:-1
 RemoveMessagesByPredicate = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 buttonFrame = ChatFrame10ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 alternativeDefaultLanguage = "Gemeinsprache"
 isInitialized = 1
 GetNumVisibleLines = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 AddOnDisplayRefreshedCallback = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 Show = <function> defined @FrameXML/FrameLocks.lua:135
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = Frame {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 flashTimer = 0
 timeVisibleSecs = 120
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 000002C5DA3901D0 {
 }
 SetInsertMode = <function> defined =[C]:-1
 originalHide = <function> defined =[C]:-1
 ScrollDown = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 Hide = <function> defined @FrameXML/FrameLocks.lua:131
 GetTextColor = <function> defined =[C]:-1
 CallOnDisplayRefreshed = <function> defined =[C]:-1
 defaultLanguage = "Gemeinsprache"
 dbg = <function> defined @Prat-3.0/services/print.lua:51
 onDisplayRefreshedCallbacks = <table> {
 }
 GatherSelectedText = <function> defined =[C]:-1
 ScrollByAmount = <function> defined =[C]:-1
 SetJustifyV = <function> defined =[C]:-1
 OnFontObjectUpdated =

0,

**Comment by plusmouse** [comment]
Did you intend to file this bug for Prat - you mention a Bagnon version at the top of the issue?

**Comment by Knakriktsur** [comment]
WOTLK 3.4.2.50375
Ger Client
Prat "Prat-3.0-3.9.32"

Hi, sorry for the late reply, wasn`t at home.
Yes this was for Prat, came back as I got another one when I just logged in and did`nt do anything.


1x FrameXML/FloatingChatFrame.lua:973: attempt to index local 'self' (a nil value)
[string "@FrameXML/FloatingChatFrame.lua"]:973: in function <FrameXML/FloatingChatFrame.lua:968>
[string "=[C]"]: in function `FCF_SetChatWindowFontSize'
[string "@Prat-3.0-3.9.32/modules/Font.lua"]:722: in function `SetFontSize'
[string "@Prat-3.0-3.9.32/modules/Font.lua"]:710: in function `ConfigureAllChatFrames'
[string "@Prat-3.0-3.9.32/modules/ChatFrames.lua"]:638: in function <Prat-3.0/modules/ChatFrames.lua:632>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `FloatingChatFrame_UpdateBackgroundAnchors'
[string "@Interface_WrathBlizzard_CombatLog/Blizzard_CombatLog.lua"]:3348: in function <...athBlizzard_CombatLog/Blizzard_CombatLog.lua:3334>
[string "@Interface_WrathBlizzard_CombatLog/Blizzard_CombatLog.lua"]:3403: in function `FCF_DockUpdate'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2707: in function `UIParentManageFramePositions'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:1958: in function <Interface_Wrath/FrameXML/UIParent.lua:1945>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2714: in function <Interface_Wrath/FrameXML/UIParent.lua:2712>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@FrameXML/BuffFrame.lua"]:379: in function `BuffFrame_UpdateAllBuffAnchors'
[string "@FrameXML/BuffFrame.lua"]:120: in function `BuffFrame_Update'
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:75: in function <...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:74>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@SharedXML/CvarUtil.lua"]:114: in function <SharedXML/CvarUtil.lua:106>

Locals:
self = nil
chatFrame = ChatFrame10 {
 0 = <userdata>
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 tellTimer = 2515.019000
 fadeDurationSecs = 3
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 2527.856000
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 CanEffectivelyFade = <function> defined =[C]:-1
 print = <function> defined @Prat-3.0/services/print.lua:47
 OnPreSizeChanged = <function> defined =[C]:-1
 GetScrollOffset = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "Chat 10"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined =[C]:-1
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 originalShow = <function> defined =[C]:-1
 RemoveMessagesByPredicate = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 buttonFrame = ChatFrame10ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 alternativeDefaultLanguage = "Gemeinsprache"
 isInitialized = 1
 GetNumVisibleLines = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 AddOnDisplayRefreshedCallback = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 Show = <function> defined @FrameXML/FrameLocks.lua:135
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = Frame {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 flashTimer = 0
 timeVisibleSecs = 120
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 00000188F89F31C0 {
 }
 SetInsertMode = <function> defined =[C]:-1
 originalHide = <function> defined =[C]:-1
 ScrollDown = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 Hide = <function> defined @FrameXML/FrameLocks.lua:131
 GetTextColor = <function> defined =[C]:-1
 CallOnDisplayRefreshed = <function> defined =[C]:-1
 defaultLanguage = "Gemeinsprache"
 dbg = <function> defined @Prat-3.0/services/print.lua:51
 onDisplayRefreshedCallbacks = <table> {
 }
 GatherSelectedText = <function> defined =[C]:-1
 ScrollByAmount = <function> defined =[C]:-1
 SetJustifyV = <function> defined =[C]:-1
 OnFontObjectUpdated =

**Comment by plusmouse** [comment]
Are you sure that this error is Prat specific, as I can't replicate the issue?

If you can try disabling Prat and trying to login again. If the error disappears (confirming its Prat) can you post your Prat saved variables so I can test with your exact settings setup.

**Comment by plusmouse** [comment]
Ok. Thanks for the response. I'll close the issue. If it does reoccur comment here and I'll reopen it.
