### ISSUE TITLE
Add Release Package

### ISSUE THREAD

**Issue by fantom8** [Legacy-of-Sylvanaar/prat-3-0#15]
Hi,

First of all, thank you for continuing the work of Sylvanaar and maintaining the best and only major chat addon for many versions of WoW running.

I was wondering if you would be willing to wrap up your releases into github-recognized packages to make it easier for users to download and stay up to date with this addon. To make it easier for you there is already a utility and guide for this process written up by BigWigs here: https://github.com/BigWigsMods/packager

Thank you and once again your work is appreciated.

**Comment by loopeey** [comment]
https://www.wowinterface.com/downloads/info10783-Prat3.0.html

This works.

**Comment by kingreboot** [comment]
That download is out of date. I would also like to see a proper release or another host like Wago or wowi if possible

**Comment by loopeey** [comment]
I mean works in download managers, yes there are lua errors atm.

**Comment by QartemisT** [comment]
Closing as pushing a more stable release shortly =]
