### ISSUE TITLE
Show Message button is not interactable

### ISSUE THREAD

**Issue by KalinPopov** [Legacy-of-Sylvanaar/prat-3-0#151]
When blizzard decides that a message is inappropriate it gets replaced but you cannot click the button to view it

![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/48012425/51ceb8e5-71a4-4cfb-93e0-c1d638f9fbcc)

**Comment by plusmouse** [comment]
Which version of Prat are you running?

**Comment by KalinPopov** [comment]
Latest official release.

**Comment by plusmouse** [comment]
This should be fixed in the latest releases. Closing.
