### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by lostamongliars** [Legacy-of-Sylvanaar/prat-3-0#152]
Chat history is not being saved anymore after the october 1st update while the "remove spam" box is ticked. works after unticking. it works while ticked in the previous "release" version, double checked to be sure.

**Comment by plusmouse** [comment]
Thanks for the bug report.

I've pushed a new fixed version `3.9.38` to Curseforge.

**Comment by plusmouse** [comment]
(it may not be available yet, still running the build script)

**Comment by xky0007** [comment]
This issue still exists at latest version.
