### ISSUE TITLE
Sequential numbers in chat

### ISSUE THREAD

**Issue by Tiiara** [Legacy-of-Sylvanaar/prat-3-0#153]
Since the last version I get sequential numbers in chat.
For every line of chat I get a an empty line with just a number.

**For example:**
some text here
1
some other notification
2
whisper from a friend
guild chat from someone
3
4

**Comment by KyrosKrane** [comment]
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/458727/5f07532f-db34-49c8-b59f-7a84c9c0ecb4)

**Comment by KyrosKrane** [comment]
Looks like this is fixed in v3.9.39
