### ISSUE TITLE
Error with IsChatLineCensored when addons (like Scrap) send chat message

### ISSUE THREAD

**Issue by Malivil** [Legacy-of-Sylvanaar/prat-3-0#154]
**Describe the bug**
Addons that print to chat (like Scrap) are triggering an error in Prat relating to censored chat

**To Reproduce**
1. Install Prat (3.9.38 or later)
2. Install Scrap (https://www.curseforge.com/wow/addons/scrap)
3. Open a vendor UI (I was testing with the repair vendor on the Tundra Mammoth)
4. See error (If you don't, mark something as scrap by dragging it on to the scrap icon in the window, then close and re-open the window)

```
Message: Interface/AddOns/Prat-3.0/addon/addon.lua:726: Usage: local isCensored = C_ChatInfo.IsChatLineCensored(chatLine)
Time: Fri Oct  6 17:18:47 2023
Count: 1
Stack: Interface/AddOns/Prat-3.0/addon/addon.lua:726: Usage: local isCensored = C_ChatInfo.IsChatLineCensored(chatLine)
[string "=[C]"]: in function `IsChatLineCensored'
[string "@Interface/AddOns/Prat-3.0/addon/addon.lua"]:726: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:615>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Scrap/addons/main/main.lua"]:239: in function `Print'
[string "@Interface/AddOns/Scrap/addons/main/main.lua"]:229: in function `PrintMoney'
[string "@Interface/AddOns/Scrap/addons/merchant/button.lua"]:211: in function `Sell'
[string "@Interface/AddOns/Scrap/addons/merchant/button.lua"]:51: in function `?'
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface/AddOns/Scrap/addons/main/main.lua"]:35: in function <Interface/AddOns/Scrap/addons/main/main.lua:35>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = nil

```

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/1238511/3579f310-f430-4c41-acf3-cd03bb6edb15)

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`
[17:00:47] Dump: value=GetBuildInfo()
[17:00:47] [1]="10.1.7",
[17:00:47] [2]="51536",
[17:00:47] [3]="Sep 26 2023",
[17:00:47] [4]=100107,
[17:00:47] [5]="",
[17:00:47] [6]=" "
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`
[17:01:13] Dump: value=Prat.Version
[17:01:13] [1]="Prat |3.0| (|3.9.39|)"

**Addons you are running**
Latest version of everything available on CurseForge:

AddonFactory
AdvancedInterfaceOptions
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Options
Altoholic_Search
Altoholic_Summary
Bartender4
CanIMogIt
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Currencies
DataStore_Garrisons
DataStore_Inventory
DataStore_Mails
DataStore_Pets
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Stats
DataStore_Talents
DBM-Aberrus
DBM-Affixes
DBM-BfA
DBM-Brawlers
DBM-BrokenIsles
DBM-Challenges
DBM-Core
DBM-Draenor
DBM-DragonIsles
DBM-GUI
DBM-Outlands
DBM-Pandaria
DBM-Party-BC
DBM-Party-BfA
DBM-Party-Cataclysm
DBM-Party-Dragonflight
DBM-Party-Legion
DBM-Party-MoP
DBM-Party-Shadowlands
DBM-Party-Vanilla
DBM-Party-WoD
DBM-Party-WotLK
DBM-Raids-BC
DBM-Raids-BfA
DBM-Raids-Cata
DBM-Raids-Dragonflight
DBM-Raids-Legion
DBM-Raids-MoP
DBM-Raids-Shadowlands
DBM-Raids-Vanilla
DBM-Raids-WoD
DBM-Raids-WoTLK
DBM-Scenario-MoP
DBM-Shadowlands
DBM-StatusBarTimers
DBM-VPVEM
DBM-WorldEvents
DejaCharacterStats
Details
Details_Compare2
Details_DataStorage
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TinyThreat
Details_Vanguard
FasterLoot
Grail
Grail-Achievements
Grail-NPCs
Grail-NPCs-deDE
Grail-NPCs-enUS
Grail-NPCs-esES
Grail-NPCs-esMX
Grail-NPCs-frFR
Grail-NPCs-itIT
Grail-NPCs-koKR
Grail-NPCs-ptBR
Grail-NPCs-ruRU
Grail-NPCs-zhCN
Grail-NPCs-zhTW
Grail-Quests
Grail-Quests-deDE
Grail-Quests-enUS
Grail-Quests-esES
Grail-Quests-esMX
Grail-Quests-frFR
Grail-Quests-itIT
Grail-Quests-koKR
Grail-Quests-ptBR
Grail-Quests-ruRU
Grail-Quests-zhCN
Grail-Quests-zhTW
Grail-Reputations
Grail-Rewards
Grail-When
IceHUD
IceHUD_Options
InFlight
InFlight_Load
InstanceAchievementTracker
Krowi_AchievementFilter
LiteMount
MinimalArchaeology
MinimapButtonButton
MountJournalEnhanced
MountsRarity
NPCTime
Nys_ToDoList
Nys_ToDoList_Backup
OmniCC
OmniCC_Config
Paste
Prat-3.0
Prat-3.0_Libraries
RareDragon
RareScanner
Rematch
ReputationWatcher
Scrap
Scrap_Config
Scrap_Merchant
SimpleQuestCounter
Socialite
Titan
TitanBag
TitanClock
TitanFarmBuddy
TitanGold
TitanItemLevel
TitanLocation
TitanLootType
TitanPerformance
TitanRepair
TitanVolume
TitanXP
TomTom
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
Wholly

**Comment by plusmouse** [comment]
This should be fixed in the latest alpha

**Comment by Malivil** [comment]
I can confirm this is fixed in the latest alpha. Thanks =)
