### ISSUE TITLE
4 LUA errors every time I login

### ISSUE THREAD

**Issue by Jaladhjin** [Legacy-of-Sylvanaar/prat-3-0#16]
**Describe the bug**
I notice these 4 bugs in bugsack every time I login

A maybe helpful screenshot: https://i.imgur.com/TTf5lIs.png

396x Prat-3.0-3.9.2c\modules\PlayerNames.lua:1798: Cannot find a library instance of "AceTab-3.0".
[string "=[C]"]: in function `error'
[string "@TheUndermineJournal\libs\LibStub.lua"]:23: in function `LibStub'
[string "@Prat-3.0-3.9.2c\modules\PlayerNames.lua"]:1798: in function `TabComplete'
[string "@Prat-3.0-3.9.2c\modules\PlayerNames.lua"]:1151: in function `OnModuleEnable'
[string "@Prat-3.0-3.9.2c\addon\modules.lua"]:189: in function <Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

396x Prat-3.0-3.9.2c\modules\AltNames.lua:1666: attempt to index upvalue 'altregistry' (a nil value)
[string "@Prat-3.0-3.9.2c\modules\AltNames.lua"]:1666: in function `OnModuleEnable'
[string "@Prat-3.0-3.9.2c\addon\modules.lua"]:189: in function <Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

397x Prat-3.0-3.9.2c\modules\AltNames.lua:1306: Cannot find a library instance of "LibAlts-1.0".
[string "=[C]"]: in function `error'
[string "@TheUndermineJournal\libs\LibStub.lua"]:23: in function `LibStub'
[string "@Prat-3.0-3.9.2c\modules\AltNames.lua"]:1306: in function `init'
[string "@Prat-3.0-3.9.2c\addon\modules.lua"]:154: in function <Prat-3.0\addon\modules.lua:147>
[string "=[C]"]: ?
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

397x Prat-3.0-3.9.2c\addon\modules.lua:284: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "LibSink-2.0".
[string "@Prat-3.0-3.9.2c\addon\addon.lua"]:236: in function <Prat-3.0\addon\addon.lua:190>
[string "=[C]"]: ?
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...dOns\BagAppraiser\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Version Information (please complete the following information):**
 - Wow Version: Retail
 - Prat Version: [12:33:29] Dump: value=Prat.Version
[12:33:29] [1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.1-1-g6978fc8|r)"

**Addons you are running**
Quite a few but Prat is my only Chat mod

**Comment by plusmouse** [comment]
This would have happened because the "Prat (libraries)" addon that ships with Prat is either disabled or not installed.
