### ISSUE TITLE
Font module wont show more than 8 chat tabs

### ISSUE THREAD

**Issue by HaraiUlfsark** [Legacy-of-Sylvanaar/prat-3-0#170]
Display - Font in prat main window will not show more than 6 of the user set chat tabs, and 2 more tabs for whispers and pet battles, when trying to set a custom font size

My proposed solution is to allow for more chat tabs to show there

I'm not well versed in coding or LUA at all, but I did find out how to change it on my side, maybe more users would like for this to be implemented for good, or even in a more correct way?

In Prat-3.0/modules/Font.lua line 611 where it reads

```
          ChatFrame1 = frameOption,
          ChatFrame2 = frameOption,
          ChatFrame3 = frameOption,
          ChatFrame4 = frameOption,
          ChatFrame5 = frameOption,
          ChatFrame6 = frameOption,
          ChatFrame7 = frameOption,
          WhisperTabs = whisperTabsOption,
          PetBattleTab = petBattleTabOption,
```

I can change it to something like 

```
          ChatFrame1 = frameOption,
          ChatFrame2 = frameOption,
          ChatFrame3 = frameOption,
          ChatFrame4 = frameOption,
          ChatFrame5 = frameOption,
          ChatFrame6 = frameOption,
          ChatFrame7 = frameOption,
          ChatFrame8 = frameOption,
          ChatFrame9 = frameOption,
          ChatFrame10 = frameOption,
          WhisperTabs = whisperTabsOption,
          PetBattleTab = petBattleTabOption,
```

It should now allow for all chat tabs to be shown, up to the max limit set by the game itself (where you cannot create more chat tabs at all)

Hope this was useful in some way

**Comment by plusmouse** [comment]
That solution looks good. Added it to the latest alpha and it will go out in the next release.
