### ISSUE TITLE
Whispers opened in a new tab will have the default backdrop texture even if disabled through Prat

### ISSUE THREAD

**Issue by Machanu** [Legacy-of-Sylvanaar/prat-3-0#171]
**Describe the bug**
When using the in-game setting under Gameplay > Social > New Whispers with it set to open whispers in a new tab, the new tab created will have the default blizzUI backdrop texture even if the backdrop textures are disabled through Prat.

**To Reproduce**
1. Go to Settings > Gameplay > Social > New Whispers, set to "New Tab"
2. Go to Prat Settings > Display Settings > Tabs > Show Tab Textures, disable (uncheck)
3. Whisper a player to open new chat tab
4. If you afterwards enable and disable "Show Tab Textures" in prat settings, it will actually disable the texture for the new chat tab, but will only do so until the tab is closed and a new one is opened.

**Expected behavior**
I suppose the tab should have no backdrop texture when a new tab is made.

**Screenshots**
![Skærmbillede 2024-01-06 184704](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/115154601/0a667eeb-5afc-471d-85f0-ba03cf20c0e4)

**Version Information (please complete the following information):**
 - Wow Version: Classic Season of Discovery (latest patch per 06-01-2024)
 - Prat Version: Prat |cff8080ff3.0|r (|cff8080ff3.9.45|r)

**Addons you are running**
I'm not running any other addons that modify the chat windows, channels or fonts. I'm using ElvUI with all chat features disabled, as I simply prefer Prat.

**Comment by plusmouse** [comment]
Fixed in the latest alpha

**Comment by Machanu** [comment]
Installed the alpha version and can confirm it works perfectly! Thank you so much! <3
