### ISSUE TITLE
Prat should not install libraries as a separate addon

### ISSUE THREAD

**Issue by KyrosKrane** [Legacy-of-Sylvanaar/prat-3-0#179]
**Is your feature request related to a problem? Please describe.**
Prat still installs its libraries as a separate addon. This can lead to odd errors if the user disables the libraries addon but keeps the main Prat addon active. It can also hinder debugging of other addons if a user disables Prat but leaves the libraries enabled.

Historically, some addons supported no-lib versions, and Prat does still have some `@no-lib-strip@` tags peppered through its source. However, Prat doesn't build a no-lib version.

**Describe the solution you'd like**
Prat should keep its libraries in a subdirectory under the main Prat directory, not as a standalone addon.

**Additional context**
Other than historical inertia, is there a benefit to keeping the libraries as a separate addon?

**Comment by KyrosKrane** [comment]
Looking back through the release history on CurseForge, the last Prat version with a no-lib build was 3.6.26 built on Dec 26, 2016.

**Comment by plusmouse** [comment]
Good point. Merged them inside the main addon now. Try it out in the latest alpha (once it finishes building)

**Comment by KyrosKrane** [comment]
A quick poke at the new alpha doesn't turn up any lua error popups, and everything seems to be working as normal in game. Thanks for the fast change!
