### ISSUE TITLE
Bug: Prefixing text causes chat line not to appear in chatbox

### ISSUE THREAD

**Issue by Johnhundred** [Legacy-of-Sylvanaar/prat-3-0#18]
To reproduce, here's the situation I experienced this in:

Two characters, both night elves, standing within Say range of each other. One is, as far as the game is concerned, speaking in Common. Each sentence, they (the one speaking Common) prefix [Darnassian] before anything they say. This causes the other person, with Prat 3.9.2c installed, to see the text show up in a chat bubble (if they're enabled) but not in their chat box.

Whether [Darnassian] is added with a prefixer addon or manually, the above will cause text to never show up in your chatbox.

**Comment by plusmouse** [comment]
Which version of WoW were you on?
I've tried it with a couple of character in Orgrimmar and it shows in chat when I type in prefixed text:
![image](https://user-images.githubusercontent.com/60280559/198880003-40a0717e-76b3-4484-84ce-05cf7716e254.png)

**Comment by plusmouse** [comment]
This issue is old, not possible to replicate, and has no new responses. Closing.
