### ISSUE TITLE
Missing Go to Bottom Button - Scroll Button Missing

### ISSUE THREAD

**Issue by Aenimma** [Legacy-of-Sylvanaar/prat-3-0#180]
**Describe the bug**
The "Go To Bottom" Button in the chat frame is hiding behind the "Scroll Down" Button.

**To Reproduce**
1. Login to the game with the addon and you will see 2 buttons 
2. Disbale the Addon and you will see 3 buttons

**Expected behavior**
Should show all 3 Buttons for Text Scrolling

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: Classic CATA 
 - Prat Version: 3.0.3.9.51

**Comment by plusmouse** [comment]
Fixed in the latest alpha, available shortly.
