### ISSUE TITLE
Show Minimize Button bug

### ISSUE THREAD

**Issue by NayooZ** [Legacy-of-Sylvanaar/prat-3-0#181]
**Describe the bug**
The show minimize button is not working for all chatframes

**To Reproduce**
I have two sets of chat frames. One on set the button is not shown, on the other it is shown.

**Expected behavior**
Should not be shown on both sets.

**Screenshots**
Attached
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/37068647/b5c004b4-c9e8-4758-bcfa-b96a3c1f1227)
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/37068647/3e081863-aacd-42fb-8688-3c04db94d4a7)
fstack of said button that is not obeying settings

**Version Information (please complete the following information):**

 - Wow Version: Classic Cata
[06:31] Dump: value=GetBuildInfo()
[06:31] [1]="4.4.0",
[06:31] [2]="54500",
[06:31] [3]="Apr 30 2024",
[06:31] [4]=40400,
[06:31] [5]="",
[06:31] [6]=" ",
[06:31] [7]=40400

 - Prat Version:[06:31] Dump: value=GetBuildInfo()
[06:31] [1]="4.4.0",
[06:31] [2]="54500",
[06:31] [3]="Apr 30 2024",
[06:31] [4]=40400,
[06:31] [5]="",
[06:31] [6]=" ",
[06:31] [7]=40400

**Comment by plusmouse** [comment]
Fixed in the latest alpha, available shortly.

**Comment by NayooZ** [comment]
Installed 3.9.52, not sure if this is the intended fix but to get rid of the minimize button I have to turn on Show Arrows - which doesn't turn on arrows but removes minimize instead.

**Comment by plusmouse** [comment]
Fixed properly in the latest alpha
