### ISSUE TITLE
Support Timerunning Chat Icon

### ISSUE THREAD

**Issue by Kanegasi** [Legacy-of-Sylvanaar/prat-3-0#184]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Blizzard's default chat places a tiny hourglass icon next to the playerlink of characters that are in Pandaria Remix. Retail characters see these icons in LFG, Trade, guild, and communities.

**Additional context**
The relevant code is simple, it's in the GetColoredName function of ChatFrame.lua (currently line 3560 and line 3540 respectively). It checks if the player GUID is a timerunner, slaps an atlas sequence just before the name, then the player link is wrapped around that. The util that adds the atlas is in Blizzard_TimerunningUtil.lua.

	if arg12 and C_ChatInfo.IsTimerunningPlayer(arg12) then
		arg2 = TimerunningUtil.AddSmallIcon(arg2);
	end

	function TimerunningUtil.AddSmallIcon(text)
		return CreateAtlasMarkup("timerunning-glues-icon", 12, 12)..text;
	end

**Comment by plusmouse** [comment]
Added to the latest alpha
