### ISSUE TITLE
Enhancement Request: Plug Into Blizzard UI Add-Ons Button

### ISSUE THREAD

**Issue by JPEscher** [Legacy-of-Sylvanaar/prat-3-0#187]
i noticed that this doesnt show in my blizzard add ons button as per the image below. would it be possible to add it there? it allows for hiding the button and a cleaner interface :)
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/46279739/74184542-b534-4295-9c99-2e3610c2aa23)

**Comment by JPEscher** [comment]
notice this in discussion with another add on i use. hope it is helpful
https://warcraft.wiki.gg/wiki/Addon_compartment

**Comment by JPEscher** [comment]
looks like a toc change. going unfortunately i haven't really worked with LUA. (i have PowerShell, Perl, Python, Bash, Java, C, and LISP, experience.)  maybe if i look and things i can propose changes that help?

attempt with manual registration style from https://warcraft.wiki.gg/wiki/Addon_compartment
i think this would be added anywhere in addon/addon.lua
```
AddonCompartmentFrame:RegisterAddon({
 text = "Prat: Chat Enhancements",
 icon = "Interface/AddOns/Prat-3.0/textures/prat-logo-dark-small.tga",
 notCheckable = true,
 func = function(button, menuInputData, menu)
	-- local buttonName = menuInputData.buttonName; -- for debugging
	-- print("Hello from the addon compartment! You clicked " .. buttonName .. "!"); -- for debugging
	Prat.ToggleOptionsWindow()
 end,
 funcOnEnter = function(button)
	MenuUtil.ShowTooltip(button, function(tooltip)
		tooltip:SetText(Prat.Version)
	end)
 end,
 funcOnLeave = function(button)
	MenuUtil.HideTooltip(button)
 end,
})
```

a quick test with that att the end of addonlua shows some success.
![image](https://github.com/user-attachments/assets/b3d802fb-7afd-40c5-b78b-05d4296470fb)
![image](https://github.com/user-attachments/assets/a6f83907-2403-4476-9d64-054f0b44ee70)
![image](https://github.com/user-attachments/assets/d27332f7-f193-4cab-b9f5-86c502d249c8)

**Comment by JPEscher** [comment]
@plusmouse you look to be the one behind commits. would you kindly review this? if you'd like i'll make a local clone and branch here for you to review & approve/commit

**Comment by JPEscher** [comment]
i got funny tonight. i have a branch locally if you'd like i can push here for you to review.
used code 
```
local aboutText = "Prat: Publications Refinement And Transmission";
AddonCompartmentFrame:RegisterAddon({
	text = aboutText,
	icon = "Interface/AddOns/Prat-3.0/textures/prat-logo-dark-small.tga",
	notCheckable = true,
	func = function(button, menuInputData, menu)
		Prat.ToggleOptionsWindow()
	end,
	funcOnEnter = function(button)
		MenuUtil.ShowTooltip(button, function(tooltip)
			tooltip:SetText(aboutText .. "\n" .. Prat.Version)
		end)
	end,
	funcOnLeave = function(button)
		MenuUtil.HideTooltip(button)
	end,
})
```
shows as 
![image](https://github.com/user-attachments/assets/763e9504-7b4b-4009-ab0f-af4817d260b7)
not sure where "@project-version@" is stored to add one to for my branch

**Comment by JPEscher** [comment]
> @plusmouse you look to be the one behind commits. would you kindly review this? if you'd like i'll make a local clone and branch from here; and then upload a pull request for you to review/edit & approve/commit

noticed the contributing.md created this as a result. i do not have classic nor cata-classic installed. would you like me to get those and then add and test those?
https://github.com/Legacy-of-Sylvanaar/prat-3-0/pull/199

**Comment by plusmouse** [comment]
Hi. I've finally added Prat to the addon compartment in the latest commit now. If you could pull it and check it works for you that would be great.
![image](https://github.com/user-attachments/assets/30c6730f-0762-4fd4-978a-55a16189d7c9)

**Comment by plusmouse** [comment]
You finding the toggle function helped :)

**Comment by JPEscher** [comment]
after getting a zip from here and switching out my Prat-3.0 folder for a test i see:
![image](https://github.com/user-attachments/assets/012ea4c1-cc0c-4388-9a92-f0fc8d211943)

**Comment by JPEscher** [comment]
clicking it works too! TY!
