### ISSUE TITLE
war within beta la erros

### ISSUE THREAD

**Issue by Axejess** [Legacy-of-Sylvanaar/prat-3-0#188]
**Describe the bug**

**To Reproduce**
1. Go to '...' Beta
2. Click on '....' load the addon
3. Scroll down to '....' error reports
4. See error:

1:
Message: ...ce/AddOns/Prat-3.0_Libraries/AceDB-3.0/AceDB-3.0.lua:264: attempt to concatenate local 'regionKey' (a nil value)
Time: Fri Jun 14 12:15:58 2024
Count: 1
Stack: ...ce/AddOns/Prat-3.0_Libraries/AceDB-3.0/AceDB-3.0.lua:264: attempt to concatenate local 'regionKey' (a nil value)

Locals: 

2:
Message: ...ts/AceGUI-3.0-SharedMediaWidgets/SharedFunctions.lua:3: attempt to call global 'LoadAddOn' (a nil value)
Time: Fri Jun 14 12:15:58 2024
Count: 1
Stack: ...ts/AceGUI-3.0-SharedMediaWidgets/SharedFunctions.lua:3: attempt to call global 'LoadAddOn' (a nil value)

Locals: 

3:
Message: ...Widgets/AceGUI-3.0-SharedMediaWidgets/FontWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)
Time: Fri Jun 14 12:15:58 2024
Count: 1
Stack: ...Widgets/AceGUI-3.0-SharedMediaWidgets/FontWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)

Locals: 

4:
Message: ...idgets/AceGUI-3.0-SharedMediaWidgets/SoundWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)
Time: Fri Jun 14 12:15:58 2024
Count: 1
Stack: ...idgets/AceGUI-3.0-SharedMediaWidgets/SoundWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)

Locals: 

5:
Message: ...ts/AceGUI-3.0-SharedMediaWidgets/StatusbarWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)
Time: Fri Jun 14 12:15:58 2024
Count: 1
Stack: ...ts/AceGUI-3.0-SharedMediaWidgets/StatusbarWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)

Locals: 

6:
Message: ...dgets/AceGUI-3.0-SharedMediaWidgets/BorderWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)
Time: Fri Jun 14 12:15:58 2024
Count: 1
Stack: ...dgets/AceGUI-3.0-SharedMediaWidgets/BorderWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)

Locals: 

7:
Message: ...s/AceGUI-3.0-SharedMediaWidgets/BackgroundWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)
Time: Fri Jun 14 12:15:58 2024
Count: 1
Stack: ...s/AceGUI-3.0-SharedMediaWidgets/BackgroundWidget.lua:9: attempt to index global 'AceGUISharedMediaWidgets' (a nil value)

Locals: 

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`

**Addons you are running**
If possible list which addons you were using when the bug occurred.

**Comment by plusmouse** [comment]
This should be resolved in the latest alpha
