### ISSUE TITLE
Wrath?

### ISSUE THREAD

**Issue by StarkSyrup** [Legacy-of-Sylvanaar/prat-3-0#19]
Is this project abandoned? Doesn't work in Wrath properly. Throws up errors and causes the screen to freeze periodically which is odd for a chat addon. Once disabled, everything is smooth again.

**Comment by Fyresparxx** [comment]
The Lua Errors I got were related to the PlayerNames Module attempting to register the PARTY_MEMBERS_CHANGED event that no longer exists. I replaced PARTY_MEMBERS_CHANGED with GROUP_ROSTER_UPDATE in the PlayerNames.Lua and the LUA errors went away and my screen stopped freezing all the time.

**Comment by Alexbeav** [comment]
> I replaced PARTY_MEMBERS_CHANGED with GROUP_ROSTER_UPDATE in the PlayerNames.Lua and the LUA errors went away and my screen stopped freezing all the time.

Can you upload that please?

**Comment by DanSheps** [comment]
I just noticed this is opened.

I opened #22 actually, however if you would like to close that I can.

Either way, I can submit a PR for this to properly account for the builds that allow GROUP_ROSTER_UPDATE

**Comment by plusmouse** [comment]
I _think_ this is fixed in the latest alpha, but would you be able to test it? https://www.curseforge.com/wow/addons/prat-3-0/files/4057106
