### ISSUE TITLE
Multiple nil and null errors on logging in with latest prat3 on TBCC

### ISSUE THREAD

**Issue by rainecheck** [Legacy-of-Sylvanaar/prat-3-0#2]
**Describe the bug**
nil and Null lua errors on logging into character

**To Reproduce**
1. Log in to a character with latest 3.9.3 version

**Expected behavior**
No lua errors

**Screenshots**
ERROR1:
```
1x Prat-3.0-3.9.3\addon\locales.lua:53: attempt to index local 'loc' (a nil value)
[string "@Prat-3.0-3.9.3\addon\locales.lua"]:53: in function `AddLocale'
[string "@Prat-3.0-3.9.3\addon\options-Options.lua"]:83: in main chunk

Locals:
L = <table> {
 AddLocale = <function> defined @Prat-3.0\addon\locales.lua:47
}
module = nil
name = "enUS"
loc = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "enUS"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'loc' (a nil value)"
GetLocale = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
```
ERROR 2:
```
1x Prat-3.0-3.9.3\addon\addon.lua:204: attempt to index global 'Options' (a nil value)
[string "@Prat-3.0-3.9.3\addon\addon.lua"]:204: in function <Prat-3.0\addon\addon.lua:190>
[string "=[C]"]: ?
[string "@Prat-3.0-3.9.3_Libraries\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...Ons\Prat-3.0_Libraries\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Prat-3.0-3.9.3_Libraries\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Prat-3.0-3.9.3_Libraries\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...Ons\Prat-3.0_Libraries\AceAddon-3.0\AceAddon-3.0.lua:615>
```
ERROR 3:
![image](https://user-images.githubusercontent.com/33798530/133536096-011f4021-0d4b-4ddb-b491-be7d757a3f38.png)

**Version Information (please complete the following information):**
 - Wow Version: Current TBC Classic. 
![image](https://user-images.githubusercontent.com/33798530/133536017-76a18dbf-ced0-4897-9bd9-e34db52c6349.png)

 - Prat Version: 
![image](https://user-images.githubusercontent.com/33798530/133536124-fb9516ab-47b8-48c1-90a5-982f5128f1ca.png)

**Addons you are running**
Errors generate even when only running Prat + Libraries, and BugSack + BugGrabber.

**Comment by humfras** [comment]
The localization wasn't properly processed in the github package.

Try https://www.wowinterface.com/downloads/getfile.php?id=10783&aid=119923
