### ISSUE TITLE
Can't update Prat via CurseForge and addon managers that use CF as source.

### ISSUE THREAD

**Issue by Voxxel** [Legacy-of-Sylvanaar/prat-3-0#20]
It's good to see you make updates for Prat 3.0 here but these new versions are not available on CF Prat page. 
The latest version here "90a8dcb" was made on Mar 16, 2022 – while the latest version on Curse is still the "g6978fc8" that was made on Feb 13, 2021.

It says the latest branch of Legacy-of-Sylvanaar/prat-3-0 master is 23 commits ahead of sylvanaar/prat-3-0 master. I can't reach any of those on Curseforge and therefore the CF (Overwolf) addon updater can't update the addon to the latest available version.

I see you're already modified the other tabs on the CF addon page (issues, source and description) but it looks like the Files tab is still linked to the old sylvanaar's Prat git instead of Legacy's Prat git – effectively blocking addon managers to update Prat. 

Please link the CF "Files" tab to Legacy's git as source.

**Comment by plusmouse** [comment]
The latest alpha release is now available from Curseforge https://www.curseforge.com/wow/addons/prat-3-0/files/4057106
