### ISSUE TITLE
On loading the game this 2 Errors I get

### ISSUE THREAD

**Issue by Venduhl** [Legacy-of-Sylvanaar/prat-3-0#207]
Hi. When I reload or start the game this is what I get:
------------------------------------------------------------------
Message: Interface/AddOns/Prat-3.0-3.9.48/addon/addon.lua:184: attempt to call field 'IsAddOnLoaded' (a nil value)
Time: Sat Aug 31 14:46:05 2024
Count: 1
Stack: Interface/AddOns/Prat-3.0-3.9.48/addon/addon.lua:184: attempt to call field 'IsAddOnLoaded' (a nil value)
[string "@Interface/AddOns/DeathNote/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/DeathNote/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DeathNote/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/DeathNote/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <.../AddOns/DeathNote/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: 
-------------------------------------------------------------------------
and
-----------------------------------------------------------------------
Message: Interface/AddOns/Prat-3.0-3.9.48/addon/options.lua:464: attempt to index field 'profiles' (a nil value)
Time: Sat Aug 31 14:46:08 2024
Count: 1
Stack: Interface/AddOns/Prat-3.0-3.9.48/addon/options.lua:464: attempt to index field 'profiles' (a nil value)
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals: parent = Frame {
 WarWithinLandingOverlay = Frame {
 }
}
overlayFrame = nil
------------------------------------------------------------------------
Don't know if you can use this but.

**Comment by plusmouse** [comment]
Update to the latest version.
