### ISSUE TITLE
WOTLK Chat Bubble Error

### ISSUE THREAD

**Issue by Eurymachus** [Legacy-of-Sylvanaar/prat-3-0#23]
**Describe the bug**

From BugSack:

217x Prat-3.0-3.10.0\modules\Bubbles.lua:479: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@Prat-3.0-3.10.0\modules\Bubbles.lua"]:479: in function `?'
[string "@Prat-3.0-3.10.0\modules\Bubbles.lua"]:533: in function `IterateChatBubbles'
[string "@Prat-3.0-3.10.0\modules\Bubbles.lua"]:437: in function `FormatBubbles'
[string "@Prat-3.0-3.10.0\modules\Bubbles.lua"]:402: in function <Prat-3.0\modules\Bubbles.lua:398>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 update = <unnamed> {
 }
 EnableModule = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 FormatCallback = <function> defined @Prat-3.0\modules\Bubbles.lua:449
 defaultModuleLibraries = <table> {
 }
 IterateChatBubbles = <function> defined @Prat-3.0\modules\Bubbles.lua:522
 SetDefaultModulePrototype = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 font = true
 name = "Prat_Bubbles"
 IsEnabled = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 FormatBubbles = <function> defined @Prat-3.0\modules\Bubbles.lua:436
 OnModuleDisable = <function> defined @Prat-3.0\modules\Bubbles.lua:432
 APLyOptions = <function> defined @Prat-3.0\modules\Bubbles.lua:410
 throttle = 0.100000
 fontsize = 14
 IsModule = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:217
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 PL = <table> {
 }
 icons = true
 SetEnabledState = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 format = true
 enabledState = true
 color = true
 shorten = false
 baseName = "Prat-3.0"
 OnModuleEnable = <function> defined @Prat-3.0\modules\Bubbles.lua:393
 RestoreDefaultsCallback = <function> defined @Prat-3.0\modules\Bubbles.lua:516
 RestoreDefaults = <function> defined @Prat-3.0\modules\Bubbles.lua:440
 IterateModules = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 OnValueChanged = <function> defined @Prat-3.0\modules\Bubbles.lua:426
 transparent = false
 GetName = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 moduleName = "Bubbles"
 defaultModuleState = true
 Disable = <function> defined @CEPGP\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
frame = <unnamed> {
 0 = <userdata>
 isSkinnedElvUI = true
 Name = <unnamed> {
 }
 holder = <unnamed> {
 }
}
fontstring = <unnamed> {
 0 = <userdata>
 fontStyle = ""
 font = "ElvUI\Core\Media\Fonts\PTSansNarrow.ttf"
 fontSize = 10.200000
}
text = ""
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 isSkinnedElvUI = true
 Name = <unnamed> {
 }
 holder = <unnamed> {
 }
}
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
MAX_CHATBUBBLE_WIDTH = 300

**To Reproduce**
1. Use the Foreman's Blackjack on a Lazy Peon

**Expected behavior**
Chat Bubble should appear for NPC but doesn't.
Does appear and there's no error when Bubble Module is disabled.

**Version Information (please complete the following information):**
 - Wow Version: Classic WOTLK 3.4.0 (46158)
 - Prat Version: Prat |cff8080ff3.0|r (|cff8080ff3.9.1|r)

**Comment by plusmouse** [comment]
Fixed in the latest alpha release https://www.curseforge.com/wow/addons/prat-3-0/files/4057106
