### ISSUE TITLE
3.9.3 not loading (Retail)

### ISSUE THREAD

**Issue by tflo** [Legacy-of-Sylvanaar/prat-3-0#3]
Updated from 3.9.2b to 3.9.3 from the Release page here, and it doesn't load at all, just throws a couple of errors (forgot to copy them, sorry).

Re-installed 3.9.2b (from WoW Interface) and it works fine.

I'm on WoW Retail 9.1.5. Let me know if you need the exact errors it threw, I'll install it again then.

Thank you, and thanks for maintaining this great add-on.

---

BTW, it would be great if install-ready packages of previous versions would be kept on Github too, so that we can roll back without going to WoW Interface.

**Comment by humfras** [comment]
Prat's github packages do not contain localizations and libraries.
The correct location for the latest release is WoWInterface (or Curseforge, in case the problem with the packager gets fixed).

**Comment by tflo** [comment]
Thanks for the info, wasn’t aware that the releases here are without libraries.
