### ISSUE TITLE
Dragonflight XML errors

### ISSUE THREAD

**Issue by LupeChristoph** [Legacy-of-Sylvanaar/prat-3-0#31]
**Describe the bug**
A number of XML errors happen on startup.

**To Reproduce**
Only activate Prat and the Prat libraries addons, plus BugGrabber and BugSack in my case.
Log in.

**Expected behavior**
No error messages.

**Version Information**
 - Wow Version:
[15:46:12] Dump: value=GetBuildInfo()
[15:46:12] [1]="10.0.0",
[15:46:12] [2]="46340",
[15:46:12] [3]="Oct 26 2022",
[15:46:12] [4]=100000 
 - Prat Version:
 [15:47:28] Dump: value=Prat.Version
[15:47:28] [1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.1|r)"

**Addons you are running**
BugGrabber
BugSack
TooManyAddons
Prat 3.0
Prat 3.0 [Libraries]

```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/popup.xml:14 Unrecognized XML: Backdrop
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/popup.xml:14 Unrecognized XML attribute: edgeFile
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/popup.xml:15 Unrecognized XML: EdgeSize
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/popup.xml:16 Unrecognized XML: AbsValue
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/popup.xml:16 Unrecognized XML attribute: val
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/pratcc.xml:7 Unrecognized XML: Backdrop
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/pratcc.xml:7 Unrecognized XML attribute: bgFile
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/pratcc.xml:7 Unrecognized XML attribute: edgeFile
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/pratcc.xml:7 Unrecognized XML attribute: tile
```
```
1x Interface/AddOns/Prat-3.0-3.9.1/frames/pratcc.xml:8 Unrecognized XML: BackgroundInsets
```

**Comment by plusmouse** [comment]
Fixed in the latest alpha release https://www.curseforge.com/wow/addons/prat-3-0/files/4057106
