### ISSUE TITLE
Pre-patch Bugs

### ISSUE THREAD

**Issue by DreamsUnderStars** [Legacy-of-Sylvanaar/prat-3-0#33]
`Message: Interface/AddOns/Prat-3.0/modules/ChatFrames.lua:610: attempt to call method 'GetMinResize' (a nil value)
Time: Sun Oct 30 12:31:47 2022
Count: 1
Stack: Interface/AddOns/Prat-3.0/modules/ChatFrames.lua:610: attempt to call method 'GetMinResize' (a nil value)
[string "@Interface/AddOns/Prat-3.0/modules/ChatFrames.lua"]:610: in function `GetDefaults'
[string "@Interface/AddOns/Prat-3.0/modules/ChatFrames.lua"]:518: in function `init'
[string "@Interface/AddOns/Prat-3.0/addon/modules.lua"]:154: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:147>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>`

`Message: Interface/AddOns/Prat-3.0/modules/ldb.lua:6: attempt to concatenate field 'FolderLocation' (a nil value)
Time: Sun Oct 30 12:31:51 2022
Count: 1
Stack: Interface/AddOns/Prat-3.0/modules/ldb.lua:6: attempt to concatenate field 'FolderLocation' (a nil value)
[string "@Interface/AddOns/Prat-3.0/modules/ldb.lua"]:6: in function `v'
[string "@Interface/AddOns/Prat-3.0/addon/addon.lua"]:317: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:315>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>`

`Message: Interface/AddOns/Prat-3.0/modules/ChatFrames.lua:625: attempt to call method 'SetMinResize' (a nil value)
Time: Sun Oct 30 12:31:51 2022
Count: 1
Stack: Interface/AddOns/Prat-3.0/modules/ChatFrames.lua:625: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/Prat-3.0/modules/ChatFrames.lua"]:625: in function `SetParameters'
[string "@Interface/AddOns/Prat-3.0/modules/ChatFrames.lua"]:599: in function `ConfigureAllChatFrames'
[string "@Interface/AddOns/Prat-3.0/modules/ChatFrames.lua"]:522: in function `OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>`

**Comment by nulian** [comment]
You can change curse to alpha version that one works in pre patch.

**Comment by plusmouse** [comment]
Those errors are fixed in the alpha (available under "View All" files in the Curseforge website)
