### ISSUE TITLE
An action was blocked because of taint from Prat-3.0 - ClearTarget()

### ISSUE THREAD

**Issue by ETSeki** [Legacy-of-Sylvanaar/prat-3-0#35]
WoW Version:10.0.0
Prat Version:3.9.3-17-g6501f52
No other Addons besides BugGrabber and BugSack

Opening the Blizzard Edit Mode while the ChatTabs module is loaded leads to a prompt that Prat has been blocked from an action only available to the Blizzard UI.
Bug sack shows
[ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.3-17-g6501f52' tried to call the protected function 'ClearTarget()'.

With the help of the taintlog and some trial and error i could find the responsible lines of code.
In the ChatTabs.lua from this repository its the Lines 262, 263, 270, 281.
In the ChatTabs.lua from the current curseforge release its the lines 572, 573, 580, 591.

<img width="416" alt="ClearTarget() Taint" src="https://user-images.githubusercontent.com/112667378/198911180-266b0d8d-a267-4c6c-b1d1-a9b13cc064e3.png">

Commenting out these lines does prevent the taint and the blocked action error but also removes the function of the module.
Sadly i dont know enough about Addon programming and Tainting to fix the problem myself and i dont know why the alpha value of the chat tabs can taint ClearTarget().

**Comment by plusmouse** [comment]
This error should have been resolved in December with a Blizzard hotfix. Open a new issue if it happens again.
