### ISSUE TITLE
AltNames ColorPicker broken

### ISSUE THREAD

**Issue by ETSeki** [Legacy-of-Sylvanaar/prat-3-0#36]
WoW Version:10.0.0
Prat Version:3.9.3-17-g6501f52
No other Addons besides BugGrabber and BugSack

Opening the AltNames module options leads to the following error and the menu doesnt get fully loaded.

1x Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceGUI-3.0-41/widgets/AceGUIWidget-ColorPicker.lua"]:105: in function `SetColor'
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1368: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1101>
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1630: in function `FeedGroup'
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1555: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1539>
[string "=[C]"]: ?
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <.../AddOns/Prat-3.0_Libraries/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:508: in function `SetSelected'
[string "@Interface/AddOns/Prat-3.0-3.9.3-17-g6501f52_Libraries/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:185: in function <...ies/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:181>

This can be hotfixed by commenting out lines 354-362 in the AltNames.lua of the repository or lines 1445-1453 in the file from the current curseforge alpha release.
This leads to the loss of the option for custon colours so i think it would be better when someone with experiene of Ace3 would fix the Color Picker.

**Comment by plusmouse** [comment]
In Dragonflight the functions used by the colour picker now require a non-nil colour. Because the module was returning a nil colour it caused an error.
