### ISSUE TITLE
Todays release broke Prat

### ISSUE THREAD

**Issue by Quazzarr** [Legacy-of-Sylvanaar/prat-3-0#38]
**Describe the bug**
Prat gets the below listed 3 errors when trying to start - and Prat does not start.

**To Reproduce**
/Reload

**Expected behavior**
Prat running ;)

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Wow Version: 10.0.0 / 46366 / Oct 27 2022 / 100000 (Retail)
 - Prat Version: Prat-3.0-3.9.3-20-g895c37b (from Curseforge / Alpha)

**Addons you are running**
I have many addons, but as the error message below mentions Kaliel's Tracker I should state her that I have version 5.0.1 installed of this addon.

**3 messages in BugSack**
1x Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/addon/modules.lua:366: attempt to call global 'geterrorhandler' (a nil value)
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/addon/modules.lua"]:366: in function `LoadModules'
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/addon/addon.lua"]:236: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:190>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

1x Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/modules/ChannelSticky.lua:437: attempt to index upvalue 'CLR' (a nil value)
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/modules/ChannelSticky.lua"]:437: in function <Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua:437>
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/modules/ChannelSticky.lua"]:457: in function `BuildChannelList'
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/modules/ChannelSticky.lua"]:342: in function `OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

1x Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/modules/PlayerNames.lua:1110: Usage: RegisterChatEvent("eventname", "methodname"): 'methodname' - method 'Prat_FrameMessage' not found on self.
[string "=[C]"]: ?
[string "@Interface/AddOns/TomTom/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:107: in function `RegisterChatEvent'
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/modules/PlayerNames.lua"]:1110: in function `OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0-3.9.3-20-g895c37b/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Quazzarr** [comment]
I just uninstalled Kaliel's Tracker, but I still get the above listed 3 errors, now just related to another addon - it seems to me, that this error most likely is derived from Prat.

**Comment by reiyooki** [comment]
Update to Prat-3.0-3.9.3-21-gb01c20d - That version seems to be working fine for me.

Also, you can directly install the updated Ace3 addon, which will give you the 10.0-compatible libs, just make sure it's the most up to date version. (r1295-alpha as of this message)

**Comment by Tiiara** [comment]
Getting (possibly) the same error with the -21 version


`4x Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/addon/modules.lua:366: attempt to call global 'geterrorhandler' (a nil value)
[string "@Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/addon/modules.lua"]:366: in function \`LoadModules'
[string "@Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/addon/addon.lua"]:236: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:190>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function \`InitializeAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>`

`4x Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/modules/ChannelSticky.lua:437: attempt to index upvalue 'CLR' (a nil value)
[string "@Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/modules/ChannelSticky.lua"]:437: in function <Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua:437>
[string "@Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/modules/ChannelSticky.lua"]:457: in function \`BuildChannelList'
[string "@Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/modules/ChannelSticky.lua"]:342: in function \`OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0-3.9.3-21-gb01c20d/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function \`EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function \`EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>`

**Comment by Anrien** [comment]
Still happening in .21

Message: Interface/AddOns/Prat-3.0/addon/modules.lua:366: attempt to call global 'geterrorhandler' (a nil value)
Time: Mon Oct 31 14:32:59 2022
Count: 1
Stack: Interface/AddOns/Prat-3.0/addon/modules.lua:366: attempt to call global 'geterrorhandler' (a nil value)
[string "@Interface/AddOns/Prat-3.0/addon/modules.lua"]:366: in function `LoadModules'
[string "@Interface/AddOns/Prat-3.0/addon/addon.lua"]:236: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:190>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:623: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals: <none>

Message: Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua:405: attempt to index upvalue 'CLR' (a nil value)
Time: Mon Oct 31 14:33:00 2022
Count: 1
Stack: Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua:405: attempt to index upvalue 'CLR' (a nil value)
[string "@Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua"]:405: in function <Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua:405>
[string "@Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua"]:425: in function `BuildChannelList'
[string "@Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua"]:310: in function `OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:630: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals: <none>

Message: Interface/AddOns/Prat-3.0/modules/PlayerNames.lua:1083: Usage: RegisterChatEvent("eventname", "methodname"): 'methodname' - method 'Prat_FrameMessage' not found on self.
Time: Mon Oct 31 14:33:00 2022
Count: 1
Stack: Interface/AddOns/Prat-3.0/modules/PlayerNames.lua:1083: Usage: RegisterChatEvent("eventname", "methodname"): 'methodname' - method 'Prat_FrameMessage' not found on self.
[string "=[C]"]: ?
[string "@Interface/AddOns/DBM-Core/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:112: in function `RegisterChatEvent'
[string "@Interface/AddOns/Prat-3.0/modules/PlayerNames.lua"]:1083: in function `OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:630: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals: <none>

Also cannot open prat config with /prat

Message: ...ter/Libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1845: AceConfigRegistry-3.0:ValidateOptionsTable(): Prat.args.display.args.Prat_ChannelSticky.plugins.ctype.say.name: expected a string or funcref, got 'nil'
Time: Mon Oct 31 14:34:11 2022
Count: 1
Stack: ...ter/Libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1845: AceConfigRegistry-3.0:ValidateOptionsTable(): Prat.args.display.args.Prat_ChannelSticky.plugins.ctype.say.name: expected a string or funcref, got 'nil'
[string "=[C]"]: ?
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:50: in function <...Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:45>
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:210: in function <...Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:205>
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:244: in function <...Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:219>
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:263: in function <...Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:219>
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:254: in function <...Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:219>
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:254: in function <...Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:219>
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:282: in function `ValidateOptionsTable'
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:324: in function `app'
[string "@Interface/AddOns/ErrorMonster/Libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1845: in function `Open'
[string "@Interface/AddOns/Prat-3.0/addon/options.lua"]:623: in function `ToggleOptionsWindow'
[string "@Interface/AddOns/Prat-3.0/addon/options.lua"]:477: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5219: in function <Interface/FrameXML/ChatFrame.lua:5165>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4883: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4919: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals: (*temporary) = "AceConfigRegistry-3.0:ValidateOptionsTable(): Prat.args.display.args.Prat_ChannelSticky.plugins.ctype.say.name: expected a string or funcref, got 'nil'"

**Comment by Quazzarr** [comment]
I installed Ace3-r1295-alpha and the latest Prat-3.0-3.9.3-22-ge560f0b, but I still get the same errors:

1x Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/addon/modules.lua:366: attempt to call global 'geterrorhandler' (a nil value)
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/addon/modules.lua"]:366: in function `LoadModules'
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/addon/addon.lua"]:236: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:190>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>


1x Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/modules/ChannelSticky.lua:405: attempt to index upvalue 'CLR' (a nil value)
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/modules/ChannelSticky.lua"]:405: in function <Interface/AddOns/Prat-3.0/modules/ChannelSticky.lua:405>
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/modules/ChannelSticky.lua"]:425: in function `BuildChannelList'
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/modules/ChannelSticky.lua"]:310: in function `OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>


1x Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/modules/PlayerNames.lua:1083: Usage: RegisterChatEvent("eventname", "methodname"): 'methodname' - method 'Prat_FrameMessage' not found on self.
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:107: in function `RegisterChatEvent'
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/modules/PlayerNames.lua"]:1083: in function `OnModuleEnable'
[string "@Interface/AddOns/Prat-3.0-3.9.3-22-ge560f0b/addon/modules.lua"]:189: in function <Interface/AddOns/Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by plusmouse** [comment]
This is fixed in the latest alpha (pending processing by Curseforge)
[Prat-3.0-3.9.3-23-gfb1ca43.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9905514/Prat-3.0-3.9.3-23-gfb1ca43.zip)

**Comment by Quazzarr** [comment]
I can confirm, all 3 reported errors now gone in this latest release. Great job, thx a lot! ;)
