### ISSUE TITLE
On Login (party members changed)

### ISSUE THREAD

**Issue by yammen1** [Legacy-of-Sylvanaar/prat-3-0#41]
getting this error every time I log in;

1x Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:137: in function `RegisterEvent'
[string "@Prat-3.0-3.9.1\modules\PlayerNames.lua"]:1132: in function `OnModuleEnable'
[string "@Prat-3.0-3.9.1\addon\modules.lua"]:189: in function <Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:536: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:626: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:611>

**Comment by QartemisT** [comment]
Update to the latest alpha version of prat :)
