### ISSUE TITLE
Feature Request: Anchor Chat Window on Left Edge

### ISSUE THREAD

**Issue by Devinmarra** [Legacy-of-Sylvanaar/prat-3-0#42]
I'm posting this on behalf of Altene who sent me a private message on Curseforge.

thank you for continuing to dev Prat 3.0 you are doing an incredible job. Do you know if it is possible or if it will be possible to anchor the chat window on the left edge of the screen in future versions?

Thanks in advance!

**Comment by agentschmitt** [comment]
i have also this problem. i disabled all buttons of the chat with the button module, but the free space of the leftside buttons cant be removed. i cant move the chat to the leftside of my screen.

**Comment by VaporAPX** [comment]
They fixed this with today's update.

**Comment by Devinmarra** [comment]
Great! I'll close this out then
