### ISSUE TITLE
Guide + Flag has disapeared from Newcomer Chat

### ISSUE THREAD

**Issue by Uggers** [Legacy-of-Sylvanaar/prat-3-0#44]
**Describe the bug**
The Name and little green flag has disappeared from Guide's names in newcomer chat

**To Reproduce**
Just be a guide and view newcomer chat.

**Screenshots**
You can see the newcomer icon, but the old Guide and flag has vanished as per 2nd screenshot
![image](https://user-images.githubusercontent.com/6855065/199348142-1c484661-53d3-4b0a-bcbf-3a917f79176c.png)

![image](https://user-images.githubusercontent.com/6855065/199348308-6c6316b6-4ab4-4353-8238-c78dc3747f08.png)

**Version Information (please complete the following information):**
 - Wow Version: 10.0.0
 - Prat Version: Prat-3.0-3.9.3-26-gae689cd.zip

**Addons you are running**
Happens with non (disabled all to see if it was a conflict)

**Comment by JPEscher** [comment]
haha i was going to submit a ticket on this. i like having the guide flag show as the murloc newbie symbol does not always show from blizzard. having both not always show is a problem.

**Comment by plusmouse** [comment]
Looking at the code this behaviour is deliberate

* It only shows the murloc if you are a mentor and a new player sent the message
* It only shows the flag if you're a new player and a mentor sent the message

**Comment by plusmouse** [comment]
Not seeing an icon _should_ mean that whoever sent the message is in the same group as you are (guide or newbie)

**Comment by Uggers** [comment]
> haha i was going to submit a ticket on this. i like having the guide flag show as the murloc newbie symbol does not always show from blizzard. having both not always show is a problem.

Its odd I'm sure it was working recently

> Looking at the code this behaviour is deliberate
> 
>     * It only shows the murloc if you are a mentor and a new player sent the message
> 
>     * It only shows the flag if you're a new player and a mentor sent the message

It would be nice to have the option to keep it to the blizzard default (shows both if you're in the channel) or a toggle to turn it to how Prat is displaying it now

**Comment by Daeveren** [comment]
It's definately weird not seeing the flag icon, makes it harder than before to see at-a-glance if another guide has answered the new player or not.

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available shortly from Curseforge). Now defaults to showing the icons.
![image](https://user-images.githubusercontent.com/60280559/199722791-fc75c15d-e262-4733-b5bd-5df8f165773c.png)

**Comment by Uggers** [comment]
Thank you, much appreciated

**Comment by Daeveren** [comment]
> Fixed in the latest alpha (available shortly from Curseforge). Now defaults to showing the icons. ![image](https://user-images.githubusercontent.com/60280559/199722791-fc75c15d-e262-4733-b5bd-5df8f165773c.png)

Tbh, just the icon (without the "Guide" text), should be enough.

**Comment by WanderingFox** [comment]
Some history as I wrote the original implementation. The guide icons were _not_ supposed to show up when you're a guide (same with murlocs if you were a new player). Not sure if that behavior has changed in 10.0, but when I implemented this originally it was a direct mirror of the behavior from Blizz's ChatFrame.lua :)

**Comment by plusmouse** [comment]
Ok. I've gone back through the code, seems it was changed so that this happens:
1. Mentor flag visible if you are in newcomers chat and a mentor or anytime any chat if you're a new newcomer
2. Murloc visible if you are a mentor and the newcomer is in any chat.

**Comment by Daeveren** [comment]
> Ok. I've gone back through the code, seems it was changed so that this happens:
> 
> 1. Mentor flag visible if you are in newcomers chat and a mentor or anytime any chat if you're a new newcomer
> 2. Murloc visible if you are a mentor and the newcomer is in any chat.

Both of these seem fine. But this is not particularly the behavior of Prat right now.
From what I've seen myself, there's 2 ways Prat differs:
1. in the newcommer chat, for the guide it now shows not just the icon, but the 'guide' text too.
2. the guide icon + guide text is shown for me (who I am guide) even in normal dungeon groups, which I'm fairly sure it should not happen (if any, it should only be shown to the newcommers in the group, on their screen, but there was no newcommer in group anyway)

**Comment by plusmouse** [comment]
1. That matches Blizzard behaviour
2. That will no longer be the case, fixed that.
