### ISSUE TITLE
Real ID Whisper space between channel and name

### ISSUE THREAD

**Issue by VaporAPX** [Legacy-of-Sylvanaar/prat-3-0#45]
I like to adjust my channel names so Real ID Whispers just say "to" and "from" and only the real ID whispers leave a space between when adjusting them with the ChannelNames module.  All other channels, including whispers work as intended.

![Bug](https://user-images.githubusercontent.com/21989751/199357473-92ff0918-1755-4b3b-9866-dbea2db78613.jpg)

**Comment by Hyphie24** [comment]
I believe it's supposed to be a Blizzard icon that it's not calling on if I remember correctly

**Comment by QartemisT** [comment]
I'm unable to replicate this issue. What version of the game are you on, and which version of prat?

**Comment by VaporAPX** [comment]
Wow version 10.0.0.46366 and Prat-3.0.3.9.3-26-gae689cd (updated through curseforge)

**Comment by VaporAPX** [comment]
Just did a quick test, disabling all mods other than Prat, and the issue still persists.

**Comment by VaporAPX** [comment]
Ok I'm an idiot. There's an option there under PlayerNames that says "Show BNet Client Icon". When this is enabled it shows the blank space. Maybe that should show an icon? But I'm more than happy to just disable it to remove the space.

Apologies, I spent so much time in the channel names tab I didn't think to go to player names until you said you couldn't replicate the issue lol.

**Comment by QartemisT** [comment]
I highly susspect it's a blizzard issue in that case then :D
