### ISSUE TITLE
Chatbox moves on reload if part of the edit mode outline is off the screen

### ISSUE THREAD

**Issue by Baz4k** [Legacy-of-Sylvanaar/prat-3-0#52]
**Describe the bug**
When you move the chat box to the upper right hand corner of the screen, you need to have some of the top and left side of the green edit box off the screen to get it completely in the corner. When you reload the game, the chatbox will have moved down and to the right to make sure all of the edit box is on the screen. It doesn't stay where you left it if some of the edit box is off the screen.

**To Reproduce**
1. Press escape and press "Edit Mode"
2. Place chat box in the top left corner of the screen so the chat window is in the corner.
3. exit edit mode
4. reload the game

**Expected behavior**
The chatbox should stay where you left it in edit mode upon reloading the game

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: retail
 - Prat Version: You get this when you log in, or anytime `![Example](https://user-images.githubusercontent.com/29839146/200053771-54dc9376-cc77-41b1-845b-520d55303109.jpg)`

**Addons you are running**
If possible list which addons you were using when the bug occurred.

**Comment by plusmouse** [comment]
This has been fixed in the latest alpha. I've just pushed the fixes to the regular releases now, which you can get from here while Curseforge finishes processing the file:
[Prat-3.0-3.9.5.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9941416/Prat-3.0-3.9.5.zip)

**Comment by Baz4k** [comment]
Awesome, thanks!
