### ISSUE TITLE
Background color no longer gets dark

### ISSUE THREAD

**Issue by pblair90** [Legacy-of-Sylvanaar/prat-3-0#54]
**Describe the bug**
Background opacity scale seems to have been cut in half, as it will no longer turn to black. Prior to updating to the latest update, my chat background (set to black) would reset on every reload or relog, but was at least able to set to black each time. Once updating, I expected this issue to be resolved. However, now the background will no longer set to black. I disable Prat, and the background sets to black. Re-enable Prat and background will only set to roughly 10% opacity.

**To Reproduce**
1. Disable Prat
2. Validate chat background is set to black and appears black with Prat disabled
3. Re-enable Prat
4. Reload UI
5. Validate background will not set to black

**Expected behavior**
Should be able to make the background of chat window black.

**Screenshots**
N/A at this time, but will produce, if needed.

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) Classic - 3.4.0 46368 Oct 27 2022 30400
 - Prat Version: Prat |cff8080ff3.0|r (|cff8080ff3.9.5|r)

**Addons you are running**
long list of addons. I have disabled all addons and only used Prat, same results.

**Comment by plusmouse** [comment]
What alpha have you set in this config pane
![image](https://user-images.githubusercontent.com/60280559/200078416-11482bb1-0f3e-49fc-945d-f7f44e13967d.png)

**Comment by pblair90** [comment]
.25

**Comment by pblair90** [comment]
ah ha, that is it, was unaware of this setting. thank you!

**Comment by Daeveren** [comment]
> ah ha, that is it, was unaware of this setting. thank you!

Things got changed in last version so now if you want to have a black background, you need to set it to 100% in the chat settings and also set it to 1 alpha in Prat.
