### ISSUE TITLE
Newcomers chat mentor and murloc icons

### ISSUE THREAD

**Issue by artazika** [Legacy-of-Sylvanaar/prat-3-0#55]
**Describe the bug**
Before the update, mentor and murloc text was hidden, only the icon was visible

**To Reproduce**
1. Write anything in chat for newbies with mentor status or wait until someone writes
2. You can see the icon and text

**Expected behavior**
Expected to see only icons without text

**Screenshots**
![image](https://user-images.githubusercontent.com/39316666/200087173-0947491a-22fd-4e66-adad-7da4428cc16f.png)
![image](https://user-images.githubusercontent.com/39316666/200087351-344f9333-e29d-41a7-96cc-37c227d068b4.png)

**Version Information (please complete the following information):**
 - Wow Version:
[1]="10.0.0",
[2]="46455",
[3]="Nov  1 2022",
[4]=100000
 - Prat Version:
[1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.5|r)"

**Addons you are running**
Large list of addons. I disabled them all, left only the right and still see this bug

**Comment by Daeveren** [comment]
This was changed in https://github.com/Legacy-of-Sylvanaar/prat-3-0/issues/44
I also would like it to behave like it used to be until recently - only show the icons.

**Comment by Daeveren** [comment]
Also a bug likely coming from https://github.com/Legacy-of-Sylvanaar/prat-3-0/issues/44 too and I think it's worth mentioning here is that I can see myself as a guide now when in a dungeon group, which I'm pretty sure should not happen outside of the Newcommer Chat

![afK4JWgCuk](https://user-images.githubusercontent.com/6321337/200092453-cce41f81-f3b1-4211-b6a9-b4df32ebd1a9.png)

**Comment by WanderingFox** [comment]
I wrote the original implementation of this. The check that's removed in #44 is what is causing it. That condition sets it to only show guide flags to newcomers and murlocs to guides.

The original implementation directly mirrored blizzard's implementation, which appears to have changed_(see [lines 3518-3533](https://github.com/Gethe/wow-ui-source/blob/f0084386950fe3dc31a1d61de33b364e268cf66b/Interface/FrameXML/ChatFrame.lua#L3518) of ChatFrame.lua for more details)

**Comment by Daeveren** [comment]
> The original implementation directly mirrored blizzard's implementation, which appears to have changed (see [lines 3518-3533]

Can you explain a little, here? How was the original implementation in Prat? What has changed in the original blizzard file? And do you mean that it changed in 10.0 in blizz file?

I have not used default chat, I've been using Chatter for retail for many years and when they added the newcommer chat and I became a guide I remember only seeing icons for new plyares/guides. When I switched over to Prat (rip Chatter), I remember it had the same behavior - only showing icons. It's just with 10.0 that it changed (guide icon no longer shown) and then with one of the alpha versions it got changed to show the icon+text for guides.

This is a small issue overall, I could live with any choices tbh, but I was wondering how it was, what changed on Blizz side etc. Ofcourse, _ideally_ the user would have configurable options in Prat settings for (show icon for new players; show text for new players; show icon for guides; show text for guides), but not sure if this is easy to implement or not.

**Comment by plusmouse** [comment]
I've now set it to follow Blizzard behaviour in the newest alpha, with converting it to options on my todo list:
1. Mentor flag visible if you are in newcomers chat and a mentor or anytime any chat if you're a new newcomer
2. Murloc visible if you are a mentor and the newcomer is in any chat.

**Comment by WanderingFox** [comment]
> > The original implementation directly mirrored blizzard's implementation, which appears to have changed (see [lines 3518-3533]
> 
> Can you explain a little, here? How was the original implementation in Prat? What has changed in the original blizzard file? And do you mean that it changed in 10.0 in blizz file?
Sorry for the confusion. By original implementation, I mean I'm the one who wrote the new comer / mentor behavior for prat initially back in BFA.
> 
> I have not used default chat, I've been using Chatter for retail for many years and when they added the newcommer chat and I became a guide I remember only seeing icons for new plyares/guides. When I switched over to Prat (rip Chatter), I remember it had the same behavior - only showing icons. It's just with 10.0 that it changed (guide icon no longer shown) and then with one of the alpha versions it got changed to show the icon+text for guides.
Prat is using the exact same logic Blizzard uses. They changed the value of `NPEV2_CHAT_USER_TAG_GUIDE` in 10.0. The reason you just noticed it was that #44 made the guide status visible to other guides.




> I've now set it to follow Blizzard behaviour in the newest alpha, with converting it to options on my todo list:
> 
> 1. Mentor flag visible if you are in newcomers chat and a mentor or anytime any chat if you're a new newcomer
> 2. Murloc visible if you are a mentor and the newcomer is in any chat.

Thanks!

**Comment by plusmouse** [comment]
Hi. Its been a while, but I'm finally at the options on my todo list. What options are wanted?

* Guide icon only (no label) in newcomers chat
* Guide icon and label in newcomers chat
* No guide icon or label in newcomers chat
* Murloc icon in newcomers chat if guide
* Murloc icon in newcomers chat if newbie

**Comment by Daeveren** [comment]
> Hi. Its been a while, but I'm finally at the options on my todo list. What options are wanted?
> 
> * Guide icon only (no label) in newcomers chat
> * Guide icon and label in newcomers chat
> * No guide icon or label in newcomers chat
> * Murloc icon in newcomers chat if guide
> * Murloc icon in newcomers chat if newbie

Would these be individually toggle-able? Or just select one of them?
For example, I'd wish to see "Guide icon and label in newcomers chat" + "Murloc icon in newcomers chat if guide"

**Comment by plusmouse** [comment]
I was thinking of having a few sets of settings
1. Murloc icon on and off in newcomers chat
2. Murloc icon on and off in not-newcomers chat
3. Guide icon and label on and off in newcomers chat (with a subsetting to remove the label)

**Comment by Daeveren** [comment]
Sounds good

**Comment by plusmouse** [comment]
Status update, not working yet, but this is what I'm looking to make work:
![image](https://user-images.githubusercontent.com/60280559/218449280-44eb946f-51de-41d7-9ea9-27c0627eb20f.png)

**Comment by plusmouse** [comment]
I've added the new module "NewcomersChat" to the latest alpha which will b available once it finishes building
