### ISSUE TITLE
Can not move chat fully to the edge of the screen

### ISSUE THREAD

**Issue by OutOfPhase87** [Legacy-of-Sylvanaar/prat-3-0#58]
**Describe the bug**
Before Blizz updated the UI we were able to fully move and snap the chat window to the edge of the screen.
In the screenshot below the chat time is at the very edge of the screen:
https://imgur.com/eDvSo8n

After UI update this is as far as the chat can be moved to the edge of the screen:

https://imgur.com/MHXdDkq
https://imgur.com/v5pLwyK

**To Reproduce**
Try to move the chat windows to the edge of the screen in Edit mode.

**Expected behavior**
We should be able to move the chat windows next to the edge of the screen as before UI update.

**Screenshots**
Screenshots added above.

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`:: 10.0.0.
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`: 3.9.1-1-g6978fc8 (from changelog.md)

**Addons you are running**
Irrelevant of addons used.

Since I'm not 100% sure if this is now impossible to achieve with the way new UI works, I've logged this issue just in case.

**Comment by plusmouse** [comment]
There's an option for that:
![image](https://user-images.githubusercontent.com/60280559/200143753-f3c71c14-58af-4b63-9bf2-e60d56a43bc4.png)

**Comment by OutOfPhase87** [comment]
Thanks for such a quick reply.
For whatever reason I do not have "Frames" available in the Display Settings options, even though the corresponding module is enabled in Modules section.

**Comment by OutOfPhase87** [comment]
Ok, this was some sort of a weird buggy behavior on my end.
Got the "Frames" settings to appear an load after reinstalling Prat.

Thank you very much, I will close this now.
