### ISSUE TITLE
Static chat frame alpha

### ISSUE THREAD

**Issue by plusmouse** [Legacy-of-Sylvanaar/prat-3-0#59]
![image](https://user-images.githubusercontent.com/60280559/200174184-0fd0bc41-1cd9-4a41-89c8-993799af1d8e.png)

**Comment by plusmouse** [comment]
@Crusherix This update should do what you want.
[Prat-3.0-3.9.6-3-g8df588f.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9945965/Prat-3.0-3.9.6-3-g8df588f.zip)

**Comment by Daeveren** [comment]
Damn @plusmouse is doing amazing stuff.
Bravo!

**Comment by Crusherix** [comment]
@plusmouse Cheers!
