### ISSUE TITLE
History only showing 10 lines.

### ISSUE THREAD

**Issue by Quartzfire** [Legacy-of-Sylvanaar/prat-3-0#60]
**Describe the bug**
My History settings are set to max.

![image](https://user-images.githubusercontent.com/76067897/200176715-fc12d891-3d06-416a-a0a4-271d00d2004a.png)

However when I go into the copychat screen, I only see 10 lines of "history". I'm sure in the past this is where I used to access my history. Sincere apologies if I'm not using the feature correctly.

**Expected behavior**
I expect to see more than a few lines of history.

** Steps to reproduce
- See volume of text in general chat, or in my test, type "/dump GetBuildInfo()" 5 times which generated about 20 lines of chat.
- Click CopyChat button
- Only see around 10 lines of chat.

![image](https://user-images.githubusercontent.com/76067897/200177210-16c60502-4593-4d3a-a7b1-806b2dc1a3e0.png)

**Version Information (please complete the following information):**
 - Wow Version: 
Dump: value=GetBuildInfo()
[1]="10.0.0",
[2]="46455",
[3]="Nov  1 2022",
[4]=100000

 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`
Dump: value=Prat.Version
[1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.6|r)"

** Addons in Use
None - only Prat.

**Comment by plusmouse** [comment]
Reviewed the code. It intentionally only copies the visible chat. If you want old chat it seems you have to scroll up and then click the copy chat button.

**Comment by plusmouse** [comment]
(find a fix in the latest alpha when its finished building)
