### ISSUE TITLE
Active alpha setting is no longer respected

### ISSUE THREAD

**Issue by WanderingFox** [Legacy-of-Sylvanaar/prat-3-0#61]
**Describe the bug**
As of the latest release or two the chat background alpha setting is ignored completely.

Note in the screenshot below both active alpha and not active alpha are set to 0, aka completely transparent, yet when mousing over the chat frame the background (set white for demonstration) still appears.

I understand that this might have been a bug/unintended behavior relating to the original implementation of the chat tab fading feature, which is perfectly fine if that's the case. Just wanted to raise awareness / petition for a feature to stop chat background fading as well.

**To Reproduce**
1. Set chat window background to something obvious, but at zero alpha
2. Set active alpha to 0
3. Set non-active alpha to 0
4. Mouse over the chat frame

**Expected behavior**
The original behavior of setting the chat tabs to 0 alpha / hid them made the chat frame background alpha also be respected. In other words the frame itself would be completely transparent.

**Screenshots**
![image](https://user-images.githubusercontent.com/2967926/200176946-3883e942-c326-400f-9218-77cf307230e6.png)

**Version Information (please complete the following information):**
 - Wow Version: Current Retail (10.0.0)
 - Prat Version: cff8080ff3.0 (cff8080ff3.9.6)

**Addons you are running**
Occurs with just prat installed.

**Comment by WanderingFox** [comment]
Edit:

It looks like it might actually be that the fading module isn't working anymore?

![image](https://user-images.githubusercontent.com/2967926/200177435-65e40974-1e5e-4bd3-8c71-97a47d25aa63.png)

It used to be disabling fading forced the background color, which is transparent the entire time. Now they fade in/out like the blizzard default regardless of what's set here (timeout doesn't work, check boxes do nothing)

**Comment by WanderingFox** [comment]
Seems to be fixed by setting `DEFAULT_CHATFRAME_ALPHA = 0`  looks like it might be related to #46 ?

**Comment by plusmouse** [comment]
If you're running https://www.curseforge.com/wow/addons/prat-3-0/files/4070182 there is a new option
![image](https://user-images.githubusercontent.com/60280559/200177737-8d0002c5-2fea-4095-b664-b41acd93c371.png)

Turn it on and then set your chat backgrounds to transparent via the Blizzard UI. They will then not fade.

**Comment by WanderingFox** [comment]
Perfect! Thanks so much, and doubly thanks for continuing maintenance on this addon :)
