### ISSUE TITLE
[Retail] Chat window can no longer be dragged to the edge of the screen

### ISSUE THREAD

**Issue by TreizeEU** [Legacy-of-Sylvanaar/prat-3-0#62]
**Describe the bug**

I just updated Prat to latest alpha today and noticed the chat frame is no longer able to be dragged to the edge of the screen, like it could a few versions ago.

And the frames module is loaded but doesn't appear to be working.

**Version Information (please complete the following information):**

WoW Version: Retail
Prat Version: 3.9.6-3-g8df588f

And I'm getting a lua error, not sure if that's related:

`8x Interface/AddOns/Prat-3.0-3.9.6-3-g8df588f/addon/locales.lua:69: Locale key framealphastatic_name is not provided.
[string "@Interface/AddOns/Prat-3.0-3.9.6-3-g8df588f/addon/addon.lua"]:236: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:190>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>`

**Comment by plusmouse** [comment]
It is related. Pushed a fixed version (being processed by Curseforge now)
[Prat-3.0-3.9.7-alpha.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9946414/Prat-3.0-3.9.7-alpha.zip)

**Comment by TreizeEU** [comment]
3.9.7-alpha seems to have fixed it, and chat put itself back where it was. :)

**Comment by plusmouse** [comment]
Great :)
