### ISSUE TITLE
Numerous (20 on load) Prat errors..

### ISSUE THREAD

**Issue by CuteOne** [Legacy-of-Sylvanaar/prat-3-0#63]
**Describe the bug**
Errors generated on character load in.
Tried deleting the addon and wtf settings and fresh install with no difference.

**Screenshots**
![image](https://user-images.githubusercontent.com/5498251/200190661-72fe9514-976d-4289-a3e3-f81260f83582.png)
![image](https://user-images.githubusercontent.com/5498251/200190693-d03b0e86-bbfa-4d94-9e19-9eaf9baf28b0.png)
![image](https://user-images.githubusercontent.com/5498251/200190707-2e5da8db-b503-4fd6-bade-3a09eb6e4a46.png)
![image](https://user-images.githubusercontent.com/5498251/200190717-144dd7b1-8a8d-479e-b03c-e187ab8dec5b.png)
![image](https://user-images.githubusercontent.com/5498251/200190730-ffa794a0-f365-4f63-bcfe-8eca83cf2e04.png)
![image](https://user-images.githubusercontent.com/5498251/200190738-62e5a3c9-13c1-4e5e-ba69-9b5aa079c89e.png)
![image](https://user-images.githubusercontent.com/5498251/200190744-b6711326-7c1a-4734-890b-855e3022ef9d.png)
![image](https://user-images.githubusercontent.com/5498251/200190751-b12251e2-ce9f-45a7-b2cc-b889113841a1.png)
![image](https://user-images.githubusercontent.com/5498251/200190759-5dcc488f-407d-4671-bc22-7817e4f26e5e.png)
![image](https://user-images.githubusercontent.com/5498251/200190764-0e7fa67e-d63b-435b-863a-5124c8f78a40.png)
![image](https://user-images.githubusercontent.com/5498251/200190768-8f258846-7406-4c2a-83a7-4245f458c714.png)
![image](https://user-images.githubusercontent.com/5498251/200190774-acdc0722-4613-4d94-88c2-29a2c2ec9087.png)
![image](https://user-images.githubusercontent.com/5498251/200190787-019b4c3f-9630-4811-98ed-eb8a518714e2.png)
![image](https://user-images.githubusercontent.com/5498251/200190797-02ffcfe3-43de-4aa4-b2c3-e1d91adcc947.png)
![image](https://user-images.githubusercontent.com/5498251/200190802-7699e8e1-fafb-4f0c-a499-c092ba526025.png)
![image](https://user-images.githubusercontent.com/5498251/200190807-861be2bc-00a5-4fca-853d-959406b14f34.png)
![image](https://user-images.githubusercontent.com/5498251/200190814-5c4b50af-db5e-4f02-b478-5e2b6da5209b.png)
![image](https://user-images.githubusercontent.com/5498251/200190824-4e44cb84-11fb-4dc4-b6a1-38beec1ed5df.png)
![image](https://user-images.githubusercontent.com/5498251/200190834-a932cd12-6b5d-4043-9637-ee8e67f545fe.png)
![image](https://user-images.githubusercontent.com/5498251/200190845-c9c36150-f99f-473a-8c9f-9cea0136e7c8.png)

**Version Information (please complete the following information):**
Retail 10.0.0 46544

**Addons you are running**
Bugsack
Buggrabber
Prat-3.0-3.9.7-alpha (also present with 3.9.6)

**Comment by plusmouse** [comment]
Do you have the Prat-3.0_Libraries addon installed and active? Also, do you have any old versions of Prat or Prat extensions installed alongside?

Can you try downloading this file specifically (I've double checked it and it works):

[Prat-3.0-3.9.7-alpha.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9946692/Prat-3.0-3.9.7-alpha.zip)

**Comment by CuteOne** [comment]
I just cleared out all my addons (copied the folder out then deleted) and tried it with just prat, seems like there was something conflicting with it as its now working with only it. Thanks for looking into it though.
