### ISSUE TITLE
Bug: No Keybindings in the Options Panel

### ISSUE THREAD

**Issue by nancikennedy** [Legacy-of-Sylvanaar/prat-3-0#64]
The keybindings for Prat are not showing up in the Options:Keybindings Panel

**Comment by plusmouse** [comment]
Fixed in the newest alpha
[Prat-3.0-3.9.8-1-gce27f09.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9961987/Prat-3.0-3.9.8-1-gce27f09.zip)
