### ISSUE TITLE
Scroll down reminder doesnt show

### ISSUE THREAD

**Issue by GregoryGH** [Legacy-of-Sylvanaar/prat-3-0#65]
Scroll down reminder doesnt show. It was in lower right corner of chat window before.

WOTLK Classic, latest Prat alpha.

**Comment by plusmouse** [comment]
I've got it. Can you screenshot your chat frame? If your chat frame isn't pushed far enough in the corner the buttons might not have swapped to the right.

![image](https://user-images.githubusercontent.com/60280559/200572401-c365dfa0-3062-48dc-b6b5-42da84fa8565.png)
![image](https://user-images.githubusercontent.com/60280559/200572437-9aa78877-7941-44f3-8c21-2d0e80e88930.png)

**Comment by plusmouse** [comment]
Closed this issue by mistake

**Comment by jmanhehe** [comment]
This has been an issue with recent updates. I used to be able to see the scrolldownreminder inside my chatbox, bottomright, with only this setting.

I have OriginalButtons Disabled, and Buttons Enabled. Havent changed any settings, but now i need to drag the chat almost out of frame for the button to show, i also can not get the scrolldownreminder to show unless i tick the "Show Arrows" box, which is quite annoying as those buttons clog my chat. 

![bild](https://user-images.githubusercontent.com/42824951/200679752-ca1669aa-1b17-4ba8-aa03-99d7e0ebf5c7.png)
![bild](https://user-images.githubusercontent.com/42824951/200680133-107c969c-7059-4351-8085-43bf9dae19cb.png)
![bild](https://user-images.githubusercontent.com/42824951/200680165-7d086362-e2b3-4d65-8ba3-b1c74cccb15c.png)

**Comment by plusmouse** [comment]
Ok. Looks like the "IsClassic" check broke in a recent release as it was never updated for Wrath Classic. That's now fixed in the latest alpha. Can you try this version and report if it fixes your problem:
[Prat-3.0-3.9.8-3-gb1cf95f.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9965483/Prat-3.0-3.9.8-3-gb1cf95f.zip)

**Comment by jmanhehe** [comment]
Can confirm, it works as it used to based on my last screenshot in previous post.

Thanks for the quick fix.

![bild](https://user-images.githubusercontent.com/42824951/200682900-309e39ec-a69d-421e-9384-0696d15cb40d.png)

**Comment by plusmouse** [comment]
Great. The change will be in the normal release when it finishes processing (for 3.9.9). Closing this issue as fixed.
