### ISSUE TITLE
Bug: TargetUnit() taint? in Edit Mode

### ISSUE THREAD

**Issue by nancikennedy** [Legacy-of-Sylvanaar/prat-3-0#66]
On Retail, with just BugSack/Grabber and Prat enabled, when opening up Edit Mode the following error occurs. Although I thought it might be for similar reasons to #35, I thought I would post it anyway since it's a different function causing the problem. 

2x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.8-1-gce27f09' tried to call the protected function 'TargetUnit()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/EditModeManager.lua"]:1513: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1457: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function <Interface/FrameXML/UIParent.lua:3129>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface/FrameXML/FloatingChatFrame.lua"]:282: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

**Comment by plusmouse** [comment]
Do you have this option on?
![image](https://user-images.githubusercontent.com/60280559/200889753-1bdc25e4-2141-47ab-84b0-fd06a2e8d9bf.png)
Or this module loaded?
![image](https://user-images.githubusercontent.com/60280559/200889849-fb0dba28-31b9-42b4-964d-0b5e0d42dc7e.png)

**Comment by nancikennedy** [comment]
I had both of those set, but had turned off the "Remember Positions" one prior to reporting the error. I just tried disabling the ChatTabs module, but I'm still getting this error after reloading with those two options disabled

**Comment by plusmouse** [comment]
Ok. So its not that. Can you run `/console taintLog 1`, then `/reload` and trigger the error. Then upload the file `[WoW Directory]/_retail_/Logs/taint.log` to here.

That should tell me where the taint error hits.

**Comment by nancikennedy** [comment]
[taint.log](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/9973768/taint.log)

**Comment by nancikennedy** [comment]
Got another taint error when trying to share a talent build. I still had the taint log enabled, so here ya go. :)


11/10 21:17:17.369  Interface/SharedXML/UIDropDownMenu.lua:973 UIDropDownMenuButton_OnClick()
11/10 21:17:17.369  An action was blocked because of taint from Prat-3.0 - CopyToClipboard()
11/10 21:17:17.369      Interface/AddOns/Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua:443 callback()
11/10 21:17:17.369      Interface/SharedXML/LoadSystem/LoadSystemTemplates.lua:26
11/10 21:17:17.369      Interface/SharedXML/SharedUIPanelTemplates.lua:2421 Frame:SetSelectedValue()
11/10 21:17:17.369      Interface/SharedXML/SharedUIPanelTemplates.lua:2373 func()
11/10 21:17:17.369      Interface/SharedXML/UIDropDownMenu.lua:1007 UIDropDownMenuButton_OnClick()
11/10 21:17:17.369      DropDownList1Button4:IDropDownMenuTemplates.xml:136_OnClick()
11/10 21:17:37.227  Interface/SharedXML/UIDropDownMenu.lua:973 UIDropDownMenuButton_OnClick()
11/10 21:17:37.227  An action was blocked because of taint from Prat-3.0 - CopyToClipboard()
11/10 21:17:37.227      Interface/AddOns/Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua:443 callback()
11/10 21:17:37.227      Interface/SharedXML/LoadSystem/LoadSystemTemplates.lua:26
11/10 21:17:37.227      Interface/SharedXML/SharedUIPanelTemplates.lua:2421 Frame:SetSelectedValue()
11/10 21:17:37.227      Interface/SharedXML/SharedUIPanelTemplates.lua:2373 func()
11/10 21:17:37.227      Interface/SharedXML/UIDropDownMenu.lua:1007 UIDropDownMenuButton_OnClick()
11/10 21:17:37.227      DropDownList1Button4:IDropDownMenuTemplates.xml:136_OnClick()
11/10 21:17:52.568  Interface/SharedXML/UIDropDownMenu.lua:973 UIDropDownMenuButton_OnClick()
11/10 21:17:52.568  An action was blocked because of taint from Prat-3.0 - CopyToClipboard()
11/10 21:17:52.568      Interface/AddOns/Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua:443 callback()
11/10 21:17:52.568      Interface/SharedXML/LoadSystem/LoadSystemTemplates.lua:26
11/10 21:17:52.568      Interface/SharedXML/SharedUIPanelTemplates.lua:2421 Frame:SetSelectedValue()
11/10 21:17:52.568      Interface/SharedXML/SharedUIPanelTemplates.lua:2373 func()
11/10 21:17:52.568      Interface/SharedXML/UIDropDownMenu.lua:1007 UIDropDownMenuButton_OnClick()
11/10 21:17:52.568      DropDownList1Button4:IDropDownMenuTemplates.xml:136_OnClick()

**Comment by plusmouse** [comment]
Can you install the latest alpha and run chat command `/pratdebug` and paste the generated text here?

**Comment by nancikennedy** [comment]
--- ENABLED---
Prat_Achievements
Prat_Bubbles
Prat_Buttons
Prat_ChannelColorMemory
Prat_ChannelNames
Prat_ChannelSticky
Prat_Clear
Prat_CopyChat
Prat_Editbox
Prat_Fading
Prat_Filtering
Prat_Font
Prat_Frames
Prat_Highlight
Prat_History
Prat_Invites
Prat_KeyBindings
Prat_Memory
Prat_Paragraph
Prat_PlayerNames
Prat_PopupMessage
Prat_Scroll
Prat_Search
Prat_ServerNames
Prat_Sounds
Prat_Substitutions
Prat_Timestamps
Prat_UrlCopy
--- INITALIZED---
Prat_Alias
Prat_AltNames
Prat_ChatLog
Prat_ChatTabs
Prat_CustomFilters
Prat_DebugModules
Prat_EventNames
Prat_HoverTips
Prat_Mentions
Prat_OriginalButtons
Prat_TellTarget

**Comment by plusmouse** [comment]
I've done some testing with your enabled modules, found that Memory will also taint if it has restored a chat profile. Do you have the option "Load Settings Automatically" enabled?
![image](https://user-images.githubusercontent.com/60280559/201647251-f9eaca42-067f-46f8-8a33-48f0515016d5.png)

**Comment by plusmouse** [comment]
This issue has probably been resolved with a hotfix in December 2022 from Blizzard. Closing.
