### ISSUE TITLE
Prat blocks essences in chamber of heart

### ISSUE THREAD

**Issue by Zasz333** [Legacy-of-Sylvanaar/prat-3-0#68]
**Describe the bug**
Im getting an error after entering the chamber of heart and right-clicked on an essence to add it to the necklace.

**Version Information (please complete the following information):**
 - Wow Version: Retail 10.0.0
 - Prat Version: 3.9.9

[ADDON_ACTION_BLOCKED] AddOn 'Prat-3.0-3.9.9' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@Interface/FrameXML/UIParent.lua"]:3086: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/StanceBar.lua"]:73: in function `UpdateState'
[string "@Interface/FrameXML/StanceBar.lua"]:12: in function <Interface/FrameXML/StanceBar.lua:10>
[string "=[C]"]: ?

**Comment by plusmouse** [comment]
Can you install the latest alpha and run chat command `/pratdebug` and paste the generated text here?

**Comment by Zasz333** [comment]
--- ENABLED---
Prat_Achievements
Prat_Bubbles
Prat_ChannelColorMemory
Prat_ChannelNames
Prat_ChannelSticky
Prat_ChatTabs
Prat_CopyChat
Prat_Editbox
Prat_Fading
Prat_Font
Prat_Frames
Prat_Highlight
Prat_History
Prat_Invites
Prat_Memory
Prat_OriginalButtons
Prat_PlayerNames
Prat_PopupMessage
Prat_Scroll
Prat_ServerNames
Prat_TellTarget
Prat_UrlCopy
--- EXISTS---
Clear
CustomFilters
EventNames
Filtering
Search
Substitutions
Timestamps
--- INITALIZED---
Prat_Alias
Prat_AltNames
Prat_Buttons
Prat_ChatLog
Prat_DebugModules
Prat_HoverTips
Prat_KeyBindings
Prat_Mentions
Prat_Paragraph
Prat_Sounds

**Comment by plusmouse** [comment]
Has this issue repeated since December 15th, as Blizzard pushed a hotfix that probably resolved this?

**Comment by plusmouse** [comment]
Closing as this is probably fixed with the mentioned hotfix.
