### ISSUE TITLE
Include Expressway font to Prat's font set

### ISSUE THREAD

**Issue by Eldranil** [Legacy-of-Sylvanaar/prat-3-0#69]
I would like the Expressway to be included in Prat's set of fonts, as it is a very clean and easy-to-read font for chats. A lot of people should be used to Expressway as it is ElvUI's default font style, and therefore it is a well-tested font choice in-game. For people wanting to move away or stay away from ElvUI, which is likely a large portion of Prat users, it might be appealing to have access to this popular font from a standalone version of Prat.

**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem.

**Describe the solution you'd like**
From my own tinkering, it should be extremely straightforward to implement. It would require adding one line to the `fonts\fonts.lua` file:

`LSM:Register("font", "Expressway", [[Interface\Addons\]] .. folder .. [[Expressway.ttf]])`

and then adding an `Expressway.ttf` file to the `fonts` folder, which is freely available from e.g.:
https://fontsgeek.com/fonts/Expressway-ExtraBold 

Note that the Expressway-ExtraBold style is the typical style used in-game by ElvUI.

**Describe alternatives you've considered**
Using the already-included font DorisPP (*sighs*).

**Additional context**
The main concern is that there might be too many specific font requests if we ask everyone, and so keeping it to a small amount may be desirable. On the other hand, Expressway should be a very popular and proved font style in-game.

**Comment by plusmouse** [comment]
You can add fonts if they register with the LibSharedMedia library. This can be done without changes to Prat and shipped as a separate addon. This is what is done with <https://www.curseforge.com/wow/addons/thai-font-sharedmedia> and the font will work with Prat.

Not going to add more fonts to Prat core though.
