### ISSUE TITLE
Lua errors on some occasions

### ISSUE THREAD

**Issue by Morwo01** [Legacy-of-Sylvanaar/prat-3-0#7]
**Describe the bug**
i get diffrent lua errors pop up's on diffrent occasions, ie:
a guildmember chats a line in /g
i reply in /g
someone post a blizzard map location-feature in /1

**To Reproduce**

Message: Interface\AddOns\Prat-3.0\modules\PopupMessage.lua:751: bad argument #1 to 'match' (string expected, got nil)
Time: Mon Jan 17 23:08:01 2022
Count: 6
Stack: Interface\AddOns\Prat-3.0\modules\PopupMessage.lua:751: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@Interface\AddOns\Prat-3.0\modules\PopupMessage.lua"]:751: in function `CheckText'
[string "@Interface\AddOns\Prat-3.0\modules\PopupMessage.lua"]:712: in function `?'
[string "@Interface\AddOns\adblock\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ock\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\adblock\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ock\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\adblock\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Prat-3.0\addon\addon.lua"]:723: in function <Interface\AddOns\Prat-3.0\addon\addon.lua:613>
[string "=(tail call)"]: ?
[string "@Interface\FrameXML\ChatFrame.lua"]:3093: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

----------------------------------

Message: Interface\AddOns\Prat-3.0\addon\locales.lua:26: attempt to index global 'Prat' (a nil value)
Time: Mon Jan 17 22:58:02 2022
Count: 1
Stack: Interface\AddOns\Prat-3.0\addon\locales.lua:26: attempt to index global 'Prat' (a nil value)
[string "@Interface\AddOns\Prat-3.0\addon\locales.lua"]:26: in function `GetNamePattern'
[string "@Interface\AddOns\Prat-3.0\modules\PopupMessage.lua"]:639: in function `OnModuleEnable'
[string "@Interface\AddOns\Prat-3.0\addon\modules.lua"]:189: in function <Interface\AddOns\Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:11609: in function `LoadAddOn'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:11624: in function `BlizzardAPIHook'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:3106: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:3078>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>

Locals: <none>

--------------------

Locals: <none>

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 current retail of today
Prat: Version: 3.9.2c
[23:12:25] [1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.1-1-g6978fc8|r)"

**Addons you are running**
on specific request

**Comment by humfras** [comment]
Looks like on of your nicknames is defective.
Should be fixed in next release.
