### ISSUE TITLE
Prat 3.0 has been blocked from an action only available to the Blizzard UI

### ISSUE THREAD

**Issue by rdforbes** [Legacy-of-Sylvanaar/prat-3-0#70]
**Describe the bug**
This error message pops up when I use the new "Edit Mode" option (right-click on my character's icon).

**To Reproduce**
1. Go to the character's icon.
2. Right Click the character's portrait icon
3. Under Other Options, select "Edit Mode" (or can be selected directly from the Game Menu)
4. See error:  Prat-3.0 has been blocked from an action only available to the Blizzard UI.  You can disable this addon and reload the UI

**Expected behavior**
When this error is encountered, it would be nice if Blizz told us what action triggered the error, which I realize is not under your control.

**Screenshots**
A screenshot is attached.

**Version Information (please complete the following information):**
 - Wow Version: Retail [1] 10.0.0.  [2] 46597.  [3] Nov 9 2022.  [4] 100000 
 - Prat Version: version 3.9.11 (WoW is running on a Mac). Version = "Prat |cff8080ff3.0|r (|cff8080ff" .. "DEBUG" .. "|r)"

**Addons you are running**
If possible list which addons you were using when the bug occurred. I get this error with no addons loaded, and the "Load out of date AddOns" not selected on the AddOn List.

![World of Warcraft 2022-11-14 17-10-27](https://user-images.githubusercontent.com/5861885/201778764-3362d87c-f94f-4cd8-96d8-ac7998657395.jpg)

**Comment by plusmouse** [comment]
Do you have the Memory or Chat Tabs modules enabled? Those are known to cause issues.

**Comment by rdforbes** [comment]
I appreciate the quick response, and for a really useful add-on!  This issue went away when I disabled Chat Tabs, as you suggested.  Thank you!

==========

On Nov 15, 2022, at 3:29 AM, plusmouse ***@***.***> wrote:

Do you have the Memory or Chat Tabs modules enabled? Those are known to cause issues.

**Comment by GrimNotepad** [comment]
This is the stack trace from this error
```
Date: 2022-11-15 18:47:31
ID: 2
Error occured in: AddOn: Prat-3.0
Count: 2
Message: Error: AddOn Prat-3.0 attempted to call a forbidden function (FocusUnit()) from a tainted execution path.
Debug:
   [string "=[C]"]: FocusUnit()
   [string "@Interface/FrameXML/EditModeManager.lua"]:1516: RefreshTargetAndFocus()
   [string "@Interface/FrameXML/EditModeManager.lua"]:1532: SetTargetAndFocusShown()
   [string "@Interface/FrameXML/EditModeManager.lua"]:1345: onBoxToggled()
   [string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:1566: OnCheckButtonClick()
   [string "*EditModeTemplates.xml:17_OnClick"]:1:
      [string "*EditModeTemplates.xml:17_OnClick"]:1
Locals:
None
AddOns:
  Swatter, v<%version%> (<%codename%>)
  Ace3, vRelease-r1294
  AceGUI30SFXWidgets, v1.2.4
  AddonFactory, v9.2.006
  AutoSellMyJunk, v1.3
  BadBoy, vv10.0.1
  BadBoyIgnore, vv10.0.1
  Bartender4, v4.13.6
  HandyNotes, vv1.6.12
  LibStub, v
  Masque, v10.0.1
  MasqueCaith, v10.0.2
  Prat30, v3.9.12
  Prat30Libraries, v
  SexyMap, vv10.0.7
  TidyPlatesThreatPlates, v11.1.0
  Titan, v6.00.07.100000
  TitanBag, v6.00.07.100000
  TitanClock, v6.00.07.100000
  TitanCurrenciesMulti, vv9.0.3
  TitanFarmBuddy, v1.2.11.100000
  TitanGold, v6.00.07.100000
  TitanItemLevel, v2.1.0.100000
  TitanLocation, v6.00.07.100000
  TitanPerformance, v6.00.07.100000
  TitanQuests, v1.1.1.90000
  TitanVolume, v6.00.07.100000
  TradeSkillMaster, vv4.11.68
  TradeSkillMasterAppHelper, vv4.11.0
  WowLua, vv1.0.3-release
  BlizRuntimeLib_enUS v10.0.2.100002 <none>
  (ck=352)


```

**Comment by skjetne** [comment]
`3x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.12' tried to call the protected function 'TargetUnit()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/EditModeManager.lua"]:1512: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1456: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:170: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:192: in function <Interface/FrameXML/EditModeManager.lua:190>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2657: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3159: in function `ShowUIPanel'
[string "@Interface/FrameXML/FloatingChatFrame.lua"]:282: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>`

**Comment by SkywardShadow** [comment]
I get this error consistently with both of those modules disabled.

**Comment by GrimNotepad** [comment]
With the Edit Mode fiasco of the DF launch on Monday, I found that the error didn't occur simply when I opened Edit Mode.
Instead, it was triggered by my having the Player and Target option checked off in the Edit Mode window

**Comment by SkywardShadow** [comment]
> With the Edit Mode fiasco of the DF launch on Monday, I found that the error didn't occur simply when I opened Edit Mode. Instead, it was triggered by my having the Player and Target option checked off in the Edit Mode window

Yesss, I can now mostly avoid this, at least. Thanks for pointing that out!

**Comment by plusmouse** [comment]
I'm pretty sure that these issues have been resolved in the December 2022 hotfix by Blizzard - and the modules work normally too. Closing this issue now.
