### ISSUE TITLE
NPC say messages show Blizzard timestamp in addition to Prat timestamp

### ISSUE THREAD

**Issue by OwenNicholson** [Legacy-of-Sylvanaar/prat-3-0#72]
**Describe the bug**
I have blizzard timestamps enabled so they appear in the Guild & Communities window chats. In Prat I have Timestamps enabled.
Prat suppresses the Blizzard timestamps in the chat window for all messages except npcs talking, where it shows the Prat timestamp and the Blizzard timestamp.

**To Reproduce**
Enable Blizzard timestamps in options as well as Prat timestamps, stand near an npc that talks in say.

**Expected behavior**
The Blizzard timestamp should be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/74915493/202482923-748c3c69-8846-4150-9877-7f68d14b650e.png)

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic)
Retail
[1]="10.0.2",
[2]="46689",
[3]="Nov 15 2022",
[4]=100002
 
- Prat Version:
[1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.12|r)"

**Addons you are running**
This happens with only Prat loaded, no other addons at all.

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available from Curseforge once it finishes processing)
[Prat-3.0-3.9.14-3-g448ed5c.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/10327706/Prat-3.0-3.9.14-3-g448ed5c.zip)
