### ISSUE TITLE
Unable to update [Libraries]

### ISSUE THREAD

**Issue by Devinmarra** [Legacy-of-Sylvanaar/prat-3-0#76]
Hello, this was sent to me via PM from curseforge user Angrypicard

For some reason my Prat 3.0 seems to be up to date but not the Prat 3.0[Libraries]. Any way to fix this or its normal since works is in progress? Do I need to delete any lua files in my WTF or not? Thanks for the good work, it's really appreciated, I am using the curse app to update but I did it myself too just to test it out.

**Comment by plusmouse** [comment]
Fixed in 3.9.13
