### ISSUE TITLE
taint: protected function 'CancelUnitBuff()'

### ISSUE THREAD

**Issue by rml9ty** [Legacy-of-Sylvanaar/prat-3-0#78]
1x [ADDON_ACTION_BLOCKED] AddOn 'Prat-3.0-3.9.12' tried to call the protected function 'CancelUnitBuff()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CancelUnitBuff'
[string "@FrameXML/BuffFrame.lua"]:710: in function <FrameXML/BuffFrame.lua:706>

trying to cancel a buff by right clicking it in combat

**Comment by plusmouse** [comment]
This is likely fixed now due to changes Blizzard have made in the last month and a bit. Going to close pre-emptively close the issue. If it isn't fixed comment here and I'll reopen.
