### ISSUE TITLE
Selected text to copy from chat

### ISSUE THREAD

**Issue by artazika** [Legacy-of-Sylvanaar/prat-3-0#79]
The area of the selected text is different from the actual selection
I think this is a problem only with the Cyrillic text

1. Play on Cyrillic wow client
2. Press Copy text
3. Try to select text
4. Area of the selected text is different from the actual selection

**Expected behavior**
The selected text must match the displayed text

**Screenshots**
![image](https://user-images.githubusercontent.com/39316666/203388000-c510fcf9-8bf6-4d0c-b3f2-3e80e40d9ab2.png)

**Version Information (please complete the following information):**
[21:07:49]Dump: value=GetBuildInfo()
[21:07:49][1]="10.0.2",
[21:07:49][2]="46702",
[21:07:49][3]="Nov 16 2022",
[21:07:49][4]=100002
[21:08:04]Dump: value=Prat.Version
[21:08:04][1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.12|r)"

**Addons you are running**
This happens without and with my addon list

**Comment by plusmouse** [comment]
![image](https://user-images.githubusercontent.com/60280559/204033935-67e36c6b-e741-40d9-b812-39f9013ccb32.png)

Do you have any font or colour settings applied?

**Comment by artazika** [comment]
can't reproduce it now, weird
perhaps some special conditions are still needed. and when I created the report it remained buggy after several relogs because of the chat history

**Comment by plusmouse** [comment]
This was recently fixed in https://github.com/Legacy-of-Sylvanaar/prat-3-0/commit/20b26fccffd0bbbfcdd90be9487edf3df104b257
