### ISSUE TITLE
Error when I open guild tab

### ISSUE THREAD

**Issue by Verteron1** [Legacy-of-Sylvanaar/prat-3-0#8]
Heyyy man, your addon is one of the best I use  in TBC. However it seems its out of date for TBC Classic, and very often WoW TBC blocks some action of it for some reason (when I open guild tab) and I have option to disable or ignore it. Can you fix this?
Thank you!

**Comment by humfras** [comment]
I can't reproduce this.
Please check if this occurs with only Prat enabled since taint caused by some AddOn can be spread through libraries such as Ace.

**Comment by QartemisT** [comment]
Non-replicatable error with no response. If this issue persists, and you're able to replicate this with only prat installed, feel free to re-open it.

**Comment by Verteron1** [comment]
Got this error often when i open guild tab, but i have multiple addons

Срдачно,
Александар Стојиљковић
Cordially,
Aleksandar Stojiljković
+381643892889

On 2. 11. 2022., at 09:35, Artemis ***@***.***> wrote:

﻿

Non-replicatable error with no response. If this issue persists, and you're able to replicate this with only prat installed, feel free to re-open it.
