### ISSUE TITLE
Lua error on new chars

### ISSUE THREAD

**Issue by Miimzy** [Legacy-of-Sylvanaar/prat-3-0#80]
11x Prat-3.0-3.9.12-1-gd3cf08e/modules/Memory.lua:691: Usage: C_ChatInfo.SwapChatChannelsByChannelIndex(firstChannelIndex, secondChannelIndex)
[string "=[C]"]: in function `SwapChatChannelsByChannelIndex'
[string "@Prat-3.0-3.9.12-1-gd3cf08e/modules/Memory.lua"]:691: in function `CheckChannels'
[string "@Prat-3.0-3.9.12-1-gd3cf08e/modules/Memory.lua"]:639: in function `func'
[string "@Details/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <...ceDetails/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = 1
(*temporary) = nil

Getting this on new characters, unable to understand what setting is causing this or if this is just a bug.

**Comment by plusmouse** [comment]
Can you try turning the memory module off?

**Comment by Miimzy** [comment]
I unchecked the Load Settings Automatically and did a /reload

No error now

I tried clicking "Load Settings" manually and then it produced the error
