### ISSUE TITLE
Channel Name Abbrievations aren't working as of 10.0 (english)

### ISSUE THREAD

**Issue by Fiveby21** [Legacy-of-Sylvanaar/prat-3-0#82]
**Describe the bug**
Channel Name Abbrievations (i.e. [G] for Guild) are not working as of 10.0

**To Reproduce**
No clue... just have channel name abbreievations enabled and use english.

**Expected behavior**
Expected behavior is that this works.

**Screenshots**
![image](https://user-images.githubusercontent.com/40151666/204063862-c19f7775-f07d-4493-a7b6-c8afc67e1058.png)
**Version Information (please complete the following information):**
 - Wow Version: 10.0.2
 - Prat Version: ![image](https://user-images.githubusercontent.com/40151666/204063893-75e08f7b-38f3-40b2-830b-fe2b9136094d.png)

**Addons you are running**
No other addons (I did a test will all addons except Prat disabled - I still have this problem)

**Comment by plusmouse** [comment]
I can't replicate this with my Prat settings
![image](https://user-images.githubusercontent.com/60280559/204090257-e004cf9b-e631-40a2-87e2-73e7b5d5ecf8.png)
![image](https://user-images.githubusercontent.com/60280559/204090396-42ed822a-e921-4ff8-b199-6815d212cfad.png)

However it looks like all the Prat stuff for chat substitutions isn't working for you. Can you attached your file
```
[WoW Directory]\_retail_\WTF\Account\[some numbers]\SavedVariables\Prat-3.0.lua
```
so I can test with your settings? Possibly another module is breaking it.

**Comment by b-thomson** [comment]
I had this same issue and found the **Substitutions** module was set to 'Don't load' by default.
Changing this to 'Enabled' and reloading my UI fixed the issue.

**Comment by plusmouse** [comment]
Closing this issue due to no response from the original poster and that there is a fix available (enable the Substitutions module)
