### ISSUE TITLE
[ADDON_ACTION_FORBIDDEN] when opening Guild Finder window

### ISSUE THREAD

**Issue by thefowles1** [Legacy-of-Sylvanaar/prat-3-0#83]
Sometimes, when opening the guild finder window, BugGrabber picks up a forbidden action in Prat.

> 2x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.12' tried to call the protected function 'GuildControlSetRank()'.
> [string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
> [string "=[C]"]: in function \`GuildControlSetRank'
> [string "@Blizzard_GuildControlUI/Blizzard_GuildControlUI.lua"]:24: in function <.../Blizzard_GuildControlUI/Blizzard_GuildControlUI.lua:7>
> [string "=[C]"]: in function \`LoadAddOn'
> [string "@FrameXML/UIParent.lua"]:536: in function \`UIParentLoadAddOn'
> [string "@FrameXML/UIParent.lua"]:823: in function \`Communities_LoadUI'
> [string "@FrameXML/UIParent.lua"]:1124: in function \`ToggleCommunitiesFrame'
> [string "@FrameXML/UIParent.lua"]:979: in function \`ToggleGuildFrame'
> [string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

**Comment by nezorflame** [comment]
Same happened for me while opening Edit Mode:
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.13' tried to call the protected function 'FocusUnit()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `FocusUnit'
[string "@FrameXML/EditModeManager.lua"]:1516: in function `RefreshTargetAndFocus'
[string "@FrameXML/EditModeManager.lua"]:1456: in function `OnEditModeEnter'
[string "@FrameXML/EditModeManager.lua"]:170: in function `EnterEditMode'
[string "@FrameXML/EditModeManager.lua"]:192: in function <FrameXML/EditModeManager.lua:190>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2657: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2561: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3159: in function <FrameXML/UIParent.lua:3138>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/UnitPopupButtons.lua"]:481: in function `OnClick'
[string "@FrameXML/UnitPopupShared.lua"]:148: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>
```

**Comment by plusmouse** [comment]
This is likely fixed with changes made in Prat and changes Blizzard has make to edit mode. If it isn't fixed comment here and I'll reopen.
