### ISSUE TITLE
Duplicate Timestamps For Emotes

### ISSUE THREAD

**Issue by Stylonious** [Legacy-of-Sylvanaar/prat-3-0#84]
**Describe the bug**
I keep the baseline WoW timestamps (Social -> Chat Timestamps) on so I can see them in the Guild/Communities pane, and I noticed last week there were a number of messages displaying duplicated timestamps. As of today's update, I am only seeing one type of message with double the timestamps, and that is for emotes like /me or /flop type inputs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable timestamps in Prat settings.
2. Turn on WoW baseline timestamps under Options -> Social -> Chat Timestamps.
3. Input any emote into the chat window.
4. See both the Prat and the WoW base UI timestamp one after another.

**Expected behaviour**
Only the Prat timestamps should be visible and it should overwrite/remove the WoW baseline timestamp - there should not be two timestamps in a row. 

**Screenshots**
![Prat timestamps2](https://user-images.githubusercontent.com/119157304/204126669-bca3b5c7-52ea-40ea-9054-827444a8852f.png)

**Version Information (please complete the following information):**
 - Wow Version: 
 [1]="10.0.2",
 [2]="46741",
 [3]="Nov 18 2022",
 [4]=100002
 - Prat.Version:
 [1]="Prat |cff8080ff3.0|r (|cff8080ff3.9.13|r)"

**Addons you are running**
If you disable everything except for Prat 3.0 this still persists. I tested it with all addons on, all addons off, and only Prat on. The above screenshot is from the last test I did after enabling everything again.

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available from Curseforge once it finishes processing)
[Prat-3.0-3.9.14-3-g448ed5c.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/10327707/Prat-3.0-3.9.14-3-g448ed5c.zip)
