### ISSUE TITLE
Addon action blocked

### ISSUE THREAD

**Issue by Zasz333** [Legacy-of-Sylvanaar/prat-3-0#85]
**Describe the bug**
I was questing for some time on the ground, got on my renewed proto-drake and the error popped up and it blocked key bind use.

**Version Information (please complete the following information):**
 - Wow Version: current Retail
 - Prat Version: 3.9.13
 
Error text:

[ADDON_ACTION_BLOCKED] AddOn 'Prat-3.0-3.9.13' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@FrameXML/UIParent.lua"]:3095: in function `UIParentManageFramePositions'
[string "@FrameXML/UIParent.lua"]:2570: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3113: in function `UIParent_ManageFramePositions'
[string "@FrameXML/EditModeManager.lua"]:640: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@FrameXML/PetActionBar.lua"]:84: in function <FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

**Comment by plusmouse** [comment]
This is likely fixed now due to changes Blizzard have made in the last month and a bit. Going to close pre-emptively close the issue. If it isn't fixed comment here and I'll reopen.
