### ISSUE TITLE
AltNames.lua:1695: Usage: SecureHookScript(object, method, [handler]): You can only hook a script on a frame object

### ISSUE THREAD

**Issue by Ookami313** [Legacy-of-Sylvanaar/prat-3-0#87]
**Describe the bug**
Loading addon causes an error to occur. Thanks.

**To Reproduce**
Enable addon in addon list and either log into the game or /reload game if already logged in.

**Expected behavior**
No errors to occur and the addon to function properly,

**Version Information (please complete the following information):**
3.0-3.9.13

2x Prat-3.0-3.9.13/modules/AltNames.lua:1695: Usage: SecureHookScript(object, method, [handler]): You can only hook a script on a frame object
[string "=[C]"]: ?
[string "@BestInSlotRedux/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:143: in function <...Ons/BestInSlotRedux/Libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@BestInSlotRedux/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:410: in function `SecureHookScript'
[string "@Prat-3.0-3.9.13/modules/AltNames.lua"]:1695: in function `HookTooltip'
[string "@Prat-3.0-3.9.13/modules/AltNames.lua"]:1633: in function `OnModuleEnable'
[string "@Prat-3.0-3.9.13/addon/modules.lua"]:189: in function <Prat-3.0/addon/modules.lua:178>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
...
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1362>
[string "=[C]"]: ?

**Comment by plusmouse** [comment]
Looks like the tooltip changes in 10.0.2 broke the AltNames module.

What would the alt names tooltip show when its for a character with the same name as an alt, but on a different connected realm? (need to figure out the details of how it worked to replicate the behaviour again when fixing it)

**Comment by plusmouse** [comment]
This should be fixed in the latest alpha (available from Curseforge shortly)
