### ISSUE TITLE
Addon action forbidden

### ISSUE THREAD

**Issue by Zasz333** [Legacy-of-Sylvanaar/prat-3-0#88]
**Describe the bug**
After using a portal or moving otherwise to another continent, chaning map ect. at some point when using a key bind this error pops up. Key binds cant be used until a /reload. Manually clicking on abilities continues to work.

**Version Information (please complete the following information):**
 - Wow Version: current Retail
 - Prat Version: 3.9.13

Error text:

[ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.13' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

Altoholic suffers from a similar problem.

**Comment by plusmouse** [comment]
This is likely fixed now due to changes Blizzard have made in the last month and a bit. Going to close pre-emptively close the issue. If it isn't fixed comment here and I'll reopen.
