### ISSUE TITLE
Addon_Action_Forbidden 'TargetUnit()'

### ISSUE THREAD

**Issue by darbiirue** [Legacy-of-Sylvanaar/prat-3-0#89]
**Describe the bug**
I tried to fly up on my dragon via dragonriding and was plagued with an error that was bad enough that the game tried to immediately disable Prat.

`1x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.13' tried to call the protected function 'TargetUnit()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@FrameXML/EditModeManager.lua"]:1519: in function `RefreshTargetAndFocus'
[string "@FrameXML/EditModeManager.lua"]:1463: in function `OnEditModeEnter'
[string "@FrameXML/EditModeManager.lua"]:170: in function `EnterEditMode'
[string "@FrameXML/EditModeManager.lua"]:192: in function <FrameXML/EditModeManager.lua:190>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2657: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2561: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3159: in function <FrameXML/UIParent.lua:3138>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/FloatingChatFrame.lua"]:282: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>`

**Expected behavior**
I should have been able to fly, but the error started happening and took over, and prevented me from being able to ascend.

**Version Information (please complete the following information):**
 - Wow Version: 10.0.2.46879
 - Prat Version: 3.0-3.9.13

**Addons you are running**
- AdiBags
- Auctionator
- Better Wardrobe and Transmog
- BugGrabber
- BugSack
- Conceal
- CrossRP
- Deadly Boss Mods (DBM)
- DeModal
- Elephant
- GTFO
- HealthBarColor - Health Bar Color
- Immersion
- Kals AutoPetSummoner
- KuiNameplates
- Leatrix Maps (Dragonflight)
- Listener
- Minimal Archaeology
- Narcissus
- npcGenerator
- OPie
- Pawn
- Postal
- Prat 3.0
- Quest Completist
- QuickCommands
- R.IO Info in TRP3 Tooltips
- Raider.IO Mythic Plus, Raid Progress, etc.
- Shared Media
- SharedMedia ClassicalFonts
- SharedMedia_Fontin
- SharedMediaAdditionalFonts
- TomTom
- Total RP 3
- Total RP 3: Extended
- WoW-Pro Guides

**Comment by plusmouse** [comment]
Has this error happened again?

**Comment by plusmouse** [comment]
This is likely fixed now due to changes Blizzard have made in the last month and a bit. Going to close pre-emptively close the issue. If it isn't fixed comment here and I'll reopen.
