### ISSUE TITLE
General (active) chat tab appearing after cut scenes even when set to fade out

### ISSUE THREAD

**Issue by addonaddict** [Legacy-of-Sylvanaar/prat-3-0#9]
**Describe the bug**
General (active) chat tab appearing after cut scenes even when set to fade out.

**To Reproduce**
1. Set tabs to fade out
2. Enter any cut scene that hides UI
3. Current chat tab (so far General for me) will appear even though rest of chat is still hidden. Mousing over this tab fixes it and it hides again

**Expected behavior**
Should not be stuck as shown after cut scenes

**Screenshots**
When it happens:
![image](https://user-images.githubusercontent.com/73442541/159569860-973add72-8ca7-48f3-be8b-b3bb983a7be6.png)

Typical behaviour:
![image](https://user-images.githubusercontent.com/73442541/159569943-c8dd9a0e-a687-4b30-8c8e-fa15a1b745c7.png)

**Version Information (please complete the following information):**
latest. Has been a bug for years with other chat addons. could be unfixable.. idk

**Addons you are running**
not other addon related

**Comment by addonaddict** [comment]
A good way to reproduce this behavior is by using addon Immersive as example. It hides the UI during quest dialog, then enables it again, the General tab will stay active until user puts mouse in chat window. Extremely annoying.
Any chance for a fix or a solution to force active bar to stay invisible?

**Comment by jayv4** [comment]
Hi there, please could we fix this as it's a bit inconvenient for full immersion UIs!

**Comment by Rezy942** [comment]
basicchatmods addon does prat's job in minimalistic fashion. Bugs present for years here with 0 feedback from author.
If that ever changes i might consider switching back.

**Comment by plusmouse** [comment]
I've installed Immersion, and started and stopped talking to several NPCs, I can't replicate the behaviour on Wrath or Retail.

**Comment by plusmouse** [comment]
This should be fixed in the latest alpha builds

**Comment by Rezy942** [comment]
Thank you so much for going after this hard-to-catch issue. I cant wait. It was a huge gripe of mine for such a long time.
Now if it was only possible to 100% fade some icons like search and copy the fading portion of addon will be flawless :)
I opened this as a separate issue.
https://github.com/Legacy-of-Sylvanaar/prat-3-0/issues/127

Even with everything hidden, those icons unfortunately seem to only fade partially, ruining the "minimalistic" aspect of fading :)
Hope this is something you can look into in the future, as currently im "forced" to disable these, even though I want them!

**Comment by plusmouse** [comment]
If this issue isn't fixed please comment here and I'll reopen it, otherwise going to assume its fixed as of 3.9.28

**Comment by Rezy942** [comment]
Thank you again for all your work. Please consider adding donation button for maintaining this wonder of an addon!

**Comment by plusmouse** [comment]
There's a link on my Github profile for that
