### ISSUE TITLE
"Unable to manually leave chat channel: Newcomer Chat"

### ISSUE THREAD

**Issue by wheatbread** [Legacy-of-Sylvanaar/prat-3-0#93]
**Describe the bug**
Whenever I log in with Prat, I get this message spammed in the chat window.

![image](https://user-images.githubusercontent.com/548824/207473330-de92c095-00f6-4603-89db-c971bedca51a.png)

**To Reproduce**
1. Be a mentor or newcomer.  (https://www.wowhead.com/news/guide-mentor-system-help-new-players-starting-out-in-shadowlands-318521)  This puts you in the newcomer chat.
2. Log in with Prat enabled.  
3. The message will appear.  

This also happens every time you reload UI.

**Expected behavior**

No messages about attempting to leave the newcomer chat.  (It's a bit alarming that it's trying to do that because I don't want to leave it...)

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: Retail 10.0.2
 - Prat Version: 3.9.13

**Addons you are running**
If possible list which addons you were using when the bug occurred.
This happens with no other addons running.

**Comment by plusmouse** [comment]
Its possible that the memory module has decide that you left the chat at some point, and is now attempting to cause that to happen again. https://github.com/Legacy-of-Sylvanaar/prat-3-0/issues/13#issuecomment-1296123386

**Comment by wheatbread** [comment]
Thank you, I unchecked the 'load settings' checkbox and also unloaded the memory module to be sure, and that fixed it.
