### ISSUE TITLE
Lua error on my bugsack. 

### ISSUE THREAD

**Issue by Milky063** [Legacy-of-Sylvanaar/prat-3-0#96]
**Describe the bug**

I have a lua error

**To Reproduce**
1. Go to '...' no idea, just notice it in my bugsack. 

**Expected behavior**
No sure, just notice it in my bugsack

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`
 - Version: 10.0.2.47213
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`
 - Version: Prat-3.0-3.9.15.zip

**Addons you are running**
If possible list which addons you were using when the bug occurred.
 I have a few of them. Chatter being one of them.

**Comment by plusmouse** [comment]
Can you copy and paste the lua error to here?

**Comment by Milky063** [comment]
I will watch out for it today, my bugsack lua error was cleared and i dont have it as of right now.

**Comment by plusmouse** [comment]
Open a new issue if you have an error again. Closing this one.
