### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by igorrebolj** [Legacy-of-Sylvanaar/prat-3-0#97]
Message: Interface/AddOns/Prat-3.0/services/patterns.lua:234: invalid capture index
Time: Wed Jan 11 22:57:25 2023
Count: 1
Stack: Interface/AddOns/Prat-3.0/services/patterns.lua:234: invalid capture index
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `gsub'
[string "@Interface/AddOns/Prat-3.0/services/patterns.lua"]:234: in function `ReplaceMatches'
[string "@Interface/AddOns/Prat-3.0/addon/addon.lua"]:701: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:612>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/ChatFrame.lua"]:3150: in function `ChatFrame_OnEvent'
[string "*FloatingChatFrame.xml:675_OnEvent"]:1: in function <[string "*FloatingChatFrame.xml:675_OnEvent"]:1>

Locals: (*temporary) = <function> defined =[C]:-1

Happened while opening alchemy table to check crafting orders

**Comment by KonstantinosKoubetsos** [comment]
Getting the same error.

**Comment by zeenk** [comment]
I'm also getting similar error
```28x Prat-3.0-3.9.15/services/patterns.lua:234: invalid capture index
[string "=[C]"]: in function `gsub'
[string "@Prat-3.0-3.9.15/services/patterns.lua"]:234: in function `ReplaceMatches'
[string "@Prat-3.0-3.9.15/addon/addon.lua"]:701: in function <Prat-3.0/addon/addon.lua:612>
[string "=(tail call)"]: ?
[string "@FrameXML/ChatFrame.lua"]:3150: in function `ChatFrame_OnEvent'
[string "*FloatingChatFrame.xml:675_OnEvent"]:1: in function <[string "*FloatingChatFrame.xml:675_OnEvent"]:1>

Locals:
(*temporary) = "LFW@##1##@@##2##@ GET YOUR FLARING COWL, ELEMENTAL PATTERNS AND LIFE BOUNDS 418 WITH %42 @##3##@@##4##@@##5##@ GET YOUR @##6##@>> 418 FLARING COWL @##7##@>. 15K FEE EVERYTHING, FREE RC!!"
(*temporary) = "@##7##@"
(*temporary) = "|cffffffff<|r|cff00ff00<%42|r|cffffffff>|r"
````

**Comment by KonstantinosKoubetsos** [comment]
Any updates on that? It's impossible to do any crafting on Valdrakken because of this LUA error spam every 1-2minutes.

**Comment by plusmouse** [comment]
I've put a fix in the latest alpha which will available after it finishes processing (I'll update this issue when it does)

**Comment by plusmouse** [comment]
I've had to revert the fix as it broke something else.

**Comment by KonstantinosKoubetsos** [comment]
Yeah the problem is back. Can I revert to the previous or it's unsafe? I don't mind something else randomly broken for a while, this problem is kinda big for crafters that stay in Valdrakken and spam trade chat.

**Comment by plusmouse** [comment]
The old version is safe
